# -*- coding: utf-8 -*-
"""Glossaire du chiffrier, partie A — résultat, budget de caisse, bilan, immos.

`IDENTIQUE` porte les chaînes qui restent telles quelles : déjà en anglais,
noms propres, en-têtes de mois. Les déclarer explicitement vaut mieux que de les
laisser filtrer par une règle : on voit qu'elles ont été regardées.
"""

IDENTIQUE = [
    'LASCLAY-RÉSULTATS', 'COGS & Team', 'Cogs (Duties incl.)', 'Transport',
    'Discount', 'Purchase Web', 'Forecast', 'Other Inputs', 'Gabriel',
    'Employer contributions', 'Account', 'Team', 'Salary hourly',
    'Salary & contributions', 'Active', 'Hourly', 'Total',
    'Production salaries', 'Sales Marketing salaries', 'Admin Salaries',
    'Pres', 'Gabriel Gouveia', 'Catherine Bédard-Mercier', 'Visa Design',
    'RSDE', 'EBITDA', 'YTD', 'Profit', 'Lasclay', 'FPA', 'PEJ-CNRC', 'PSCE',
    'CAN Export-PCAN', 'Ville de Québec', 'Programme Innovation MEI',
    'Merchant Growth', 'Shopify', 'BDC', 'Eko-Terre', 'Vegeto', 'BMB',
    'La Ruche', 'Accord D', 'PayPal', 'Etsy',
    # en-têtes de mois, déjà abrégés à l'anglaise dans le classeur
    'Dec. 2023', 'Dec. 2024', 'Dec. 2025', 'Dec. 2026', 'Dec. 2027', 'Dec. 2028',
    'Jan. 2024', 'Jan. 2025', 'Jan. 2026', 'Jan. 2027', 'Jan. 2028', 'Jan. 2029',
    'Feb. 2024', 'Feb. 2025', 'Feb. 2026', 'Feb. 2027', 'Feb. 2028', 'Feb. 2029',
    'Mar. 2024', 'Mar. 2025', 'Mar. 2026', 'Mar. 2027', 'Mar. 2028', 'Mar. 2029',
    'Apr. 2024', 'Apr. 2025', 'Apr. 2026', 'Apr. 2027', 'Apr. 2028', 'Apr. 2029',
    'May 2024', 'May 2025', 'May 2026', 'May 2027', 'May 2028', 'May 2029',
    'Jun. 2024', 'Jun. 2025', 'Jun. 2026', 'Jun. 2027', 'Jun. 2028', 'Jun. 2029',
    'Jul. 2024', 'Jul. 2025', 'Jul. 2026', 'Jul. 2027', 'Jul. 2028', 'Jul. 2029',
    'Aug. 2025', 'Aug. 2024', 'Aug. 2026', 'Aug. 2027', 'Aug. 2028', 'Aug. 2029',
    'Sept. 2023', 'Sept. 2026', 'Sept. 2027', 'Sept. 2028',
    'Oct.2023', 'Oct.2026', 'Oct.2027', 'Oct.2028',
    'Nov. 2023', 'Nov. 2026', 'Nov. 2027', 'Nov. 2028',
    'Total 2023-2024', 'Total 2024-2025', 'Total 2025-2026',
    'Total 2026-2027', 'Total 2027-2028', 'Total 2028-2029',
]

TRADUIT = {
    # ------------------------------------------------- en-têtes du résultat
    "Pour l'exercice se terminant le 31 AOÛT 2024":
        'For the fiscal year ending 31 AUGUST 2024',
    "Pour l'exercice se terminant le 31 AOÛT 2025":
        'For the fiscal year ending 31 AUGUST 2025',
    "Pour l'exercice se terminant le 31 AOÛT 2026-27-28-29":
        'For the fiscal years ending 31 AUGUST 2026-27-28-29',
    'Actuel': 'Actual',
    'Prévision': 'Forecast',
    'PRÉVISIONS': 'FORECAST',
    '% Réel/prévisions': '% actual / forecast',
    'Dates mois >': 'Month dates >',
    'Janvier': 'January',
    'Mai à Août': 'May to August',
    'Septembre à Avril': 'September to April',

    # ------------------------------------------------------------- revenus
    'Revenus': 'Revenue',
    'Revenus Cumulatifs': 'Cumulative revenue',
    'Revenus Prévisions': 'Forecast revenue',
    'Croissance des ventes': 'Sales growth',
    'Croissance mensuelle': 'Monthly growth',
    'Croissance cumulative': 'Cumulative growth',
    'Escompte': 'Discount',
    'Ventes B2C -CAN': 'B2C sales — CAN',
    'Ventes B2C - USA': 'B2C sales — USA',
    'Ventes B2B-Distributeurs et autres': 'B2B sales — distributors and other',
    'Escomptes de ventes-CAN': 'Sales discounts — CAN',
    'Escomptes de ventes-USA': 'Sales discounts — USA',
    'Total Escomptes de ventes': 'Total sales discounts',
    '% des Escomptes sur les revenus': 'Discounts as % of revenue',
    'Ventes escomptées': 'Sales after discounts',
    'Transport sur ventes-Revenus CAN': 'Shipping on sales — revenue CAN',
    'Transport sur ventes-Revenus USA': 'Shipping on sales — revenue USA',
    'Transport sur ventes-Coûts': 'Shipping on sales — cost',
    'Transport net': 'Net shipping',
    '% de transport net sur les Revenus': 'Net shipping as % of revenue',
    'Ventes nettes': 'Net sales',
    'Ventes 2026 cumulatives': 'Cumulative 2026 sales',
    '2025 Ventes nettes': '2025 net sales',
    '2025 ventes cumulatives': 'Cumulative 2025 sales',

    # -------------------------------------------- coût des marchandises
    'Coût des marchandises vendues': 'Cost of goods sold',
    'Achats fournitures et MP': 'Purchases of supplies and raw materials',
    'Transport sur achats': 'Freight on purchases',
    '% transport sur achat': 'Freight on purchases as %',
    'Sous-traitance': 'Subcontracting',
    'Sous-traitance assemblage': 'Assembly subcontracting',
    'MOD-Production': 'Direct production labour',
    '% MOD et production': 'Direct labour and production as %',
    'Inventaire de fin-PF et MP': 'Closing inventory — finished goods and materials',
    'Contribution marginale': 'Contribution margin',
    '% Contribution marginale': 'Contribution margin %',
    'Marge Brute': 'Gross margin',
    '% Marge Brute': 'Gross margin %',
    'Frais généraux': 'Overhead',
    'Frais généraux en % des revenus': 'Overhead as % of revenue',
    'Frais généraux en % du CMV': 'Overhead as % of COGS',

    # --------------------------------------------------- charges d'exploitation
    'Fournitures d\'expédition': 'Shipping supplies',
    'Frais shopify': 'Shopify fees',
    'Salaires': 'Salaries',
    'Salaires et BM - Développement et RSDE':
        'Salaries and benefits — development and SR&ED',
    'Salaires et BM - Marketing': 'Salaries and benefits — marketing',
    'Salaires et BM - Administration et RH':
        'Salaries and benefits — administration and HR',
    'Salaires de ventes et expédition': 'Sales and shipping salaries',
    'Ressource expédition (saisonnier)': 'Shipping resource (seasonal)',
    'RSDE Matériaux': 'SR&ED materials',
    'Sous-traitant - RSDE': 'SR&ED subcontractor',
    'Frais de carburant et immatriculation': 'Fuel and vehicle registration',
    'Entretien et réparations véhicule': 'Vehicle maintenance and repairs',
    'Autres frais de transport': 'Other transport costs',
    'Entretien et réparation équipement': 'Equipment maintenance and repairs',
    'Amortissement camion': 'Truck depreciation',
    'Amortissement équipement': 'Equipment depreciation',
    'Amortissement amélioration locatives': 'Leasehold improvement depreciation',
    'Amortissement matériel informatique': 'Computer equipment depreciation',
    'Fournitures et petits outils': 'Supplies and small tools',
    'Loyer': 'Rent',
    'Abonnement logiciel': 'Software subscription',
    'License logiciel - Design': 'Software licence — design',
    'License logiciel - marketing': 'Software licence — marketing',
    'Sous traitance Design': 'Design subcontracting',
    'Designer industriel': 'Industrial designer',
    'Ressource marketing': 'Marketing resource',
    'par année': 'per year',
    'Frais de ventes': 'Selling expenses',
    'Frais de déplacement': 'Travel expenses',
    'Repas et représentation': 'Meals and entertainment',
    'Télécommunication': 'Telecommunications',
    'Site web': 'Website',
    'Outils de ventes en ligne': 'E-commerce tools',
    '% des frais de ventes sur les revenus': 'Selling expenses as % of revenue',
    'Frais de marketing': 'Marketing expenses',
    'Publicité numériques': 'Digital advertising',
    'Autres publicité': 'Other advertising',
    'Autres frais marketing': 'Other marketing expenses',
    'Sous-traitant marketing': 'Marketing subcontractor',
    'Production de contenu': 'Content production',
    'Évènement et salon': 'Events and trade shows',
    'Cartes cadeaux promotionnelles': 'Promotional gift cards',
    'Commandites': 'Sponsorships',
    'Frais de marketing en % des revenus': 'Marketing expenses as % of revenue',
    'Administration': 'Administration',
    'Honoraire professionnel - légal et conseil':
        'Professional fees — legal and advisory',
    'Honoraire professionnel - comptabilité': 'Professional fees — accounting',
    'Honoraire professionnel-autres': 'Professional fees — other',
    "Autres frais d'administration": 'Other administrative expenses',
    'Assurance - bien responsabilité': 'Insurance — property and liability',
    'Outils de gestion Admin et RH': 'Admin and HR management tools',
    'Culture et RH': 'Culture and HR',
    'Repas et déplacements-Admin': 'Meals and travel — admin',
    'Frais paye': 'Payroll fees',
    'Frais de formation': 'Training expenses',
    "Frais d'administration en % des revenus":
        'Administrative expenses as % of revenue',
    'Frais financiers': 'Finance costs',
    'Frais bancaires': 'Bank charges',
    'Frais paypal': 'PayPal fees',
    'Frais Etsy': 'Etsy fees',
    'Intérêts sur marge de crédit': 'Interest on line of credit',
    'Intérêts sur prêt accord D': 'Interest on Accord D loan',
    'Intérêts sur prêt BDC FDR': 'Interest on BDC working capital loan',
    'Intérêts et pénalités': 'Interest and penalties',
    'Frais intérêts prêt shopify': 'Interest on Shopify loan',
    'Gain/Perte sur taux de change': 'Foreign exchange gain / loss',
    'Frais financiers en % des revenus': 'Finance costs as % of revenue',
    '(Autres revenus) Autres dépenses': '(Other income) Other expenses',

    # -------------------------------------------------- sous-totaux d'équipe
    'MOD requise': 'Direct labour required',
    'Heures été': 'Summer hours',
    'Heures hiver': 'Winter hours',
    'Sous-total Prod': 'Subtotal — production',
    'Sous-total R&D': 'Subtotal — R&D',
    'Sous-total Ventes/Service': 'Subtotal — sales / service',
    'Sous-total Marketing': 'Subtotal — marketing',
    'Sous-total Admin': 'Subtotal — admin',
    "FENÊTRES D'ACTIVITÉ DES RESSOURCES (pilotent les prévisions salariales)":
        'RESOURCE ACTIVITY WINDOWS (these drive the salary forecast)',
    'Ressource': 'Resource',
    'Taux $/h': 'Rate $/h',
    'Heures/sem': 'Hours/week',
    'Actif à partir de': 'Active from',
    'Actif jusqu’à': 'Active until',
    'Mois saisonniers (vide = tous)': 'Seasonal months (blank = all)',
    'voir fenêtres L44': 'see activity windows, L44',

    # ------------------------------------------------------ aides publiques
    'R & D, Innovation et Standardisation': 'R&D, innovation and standardisation',
    'Remboursement TVQ': 'QST refund',
    'Visa Design - RSDE Crédits impôts': 'Visa Design — SR&ED tax credits',
    'Subvention Privée': 'Private grant',
    "Emploi d'été Canada": 'Canada Summer Jobs',
    'Marketing, commercialisation et exportation':
        'Marketing, commercialisation and export',
    "Revenus d'intérêts": 'Interest income',
    'Remise carte de crédit': 'Credit card rebate',

    # ----------------------------------------------------------- résultat
    'Profit (Perte) avant impôts': 'Profit (loss) before tax',
    'Impôts': 'Income tax',
    'Profit ( perte) après impôts': 'Profit (loss) after tax',
    'Profit ( perte) après impôts cumulé': 'Cumulative profit (loss) after tax',
    'Amortissements': 'Depreciation',
    'Intérêts': 'Interest',

    # ------------------------------------------------------- fonds de roulement
    'VARIATION FONDS DE ROULEMENT': 'CHANGE IN WORKING CAPITAL',
    'TOTAL VARIATION FONDS DE ROULEMENT': 'TOTAL CHANGE IN WORKING CAPITAL',
    'Comptes recevables': 'Accounts receivable',
    'Cartes cadeaux': 'Gift cards',
    'Comptes payables': 'Accounts payable',
    'Cartes de crédit': 'Credit cards',
    "Revenus perçus d'avance": 'Deferred revenue',
    'Impôts à payer': 'Income tax payable',
    'Taxes à payer': 'Sales tax payable',
    'Crédit impôts à recevoir': 'Tax credits receivable',
    "ACTIVITÉS D'INVESTISSEMENT": 'INVESTING ACTIVITIES',
    "TOTAL ACTIVITÉS D'INVESTISSEMENT": 'TOTAL INVESTING ACTIVITIES',
    'Immobilisations': 'Capital assets',
    'Actifs incorporels': 'Intangible assets',
    'ACTIVITÉS DE FINANCEMENT': 'FINANCING ACTIVITIES',
    'TOTAL ACTIVITÉS DE FINANCEMENT': 'TOTAL FINANCING ACTIVITIES',
    'Emprunt Shopify': 'Shopify loan',
    'Prêt Accord D': 'Accord D loan',
    'Prêt privé': 'Private loan',
    'Remboursement capital BDC': 'BDC principal repayment',
    'Avance actionnaire': 'Shareholder advance',
    'Variation liquidités': 'Change in cash',

    # ------------------------------------------------------ budget de caisse
    'Budget de caisse': 'Cash budget',
    'Encaissement :': 'Cash in:',
    'Comptes à recevoir': 'Accounts receivable',
    'Ventes en ligne': 'Online sales',
    "Crédits d'impôts RSDE,Visa Design": 'SR&ED and Visa Design tax credits',
    'Décaissement : (incluant paye)': 'Cash out: (including payroll)',
    'Achats matières premières': 'Raw material purchases',
    'Autres dépenses variées': 'Other miscellaneous expenses',
    'Autres frais généraux': 'Other overhead',
    "Frais d'administration": 'Administrative expenses',
    'Frais courus à payer': 'Accrued liabilities',
    'Intérêts sur prêts privés': 'Interest on private loans',
    'Intérêts Merchant Growth': 'Merchant Growth interest',
    'Ajustement timing sous-traitance BMB (acompte 40% M-3, solde 60% M-1)':
        'BMB subcontracting timing adjustment (40% deposit M-3, 60% balance M-1)',
    'Impôt à payer': 'Income tax payable',
    'Achat immobilisations': 'Purchase of capital assets',
    'Subventions (La Ruche 50k, nov. 2026)': 'Grants (La Ruche 50k, Nov. 2026)',
    'PO Vegeto Eko-Terre: cash réel (août/déc/mars) vs facturation (juil/oct/jan)':
        'Vegeto Eko-Terre PO: actual cash (Aug/Dec/Mar) vs invoicing (Jul/Oct/Jan)',
    'Variation de trésorerie': 'Change in cash',
    'BDC FDR (nouvelle dette)': 'BDC working capital (new debt)',
    'Trésorerie cumulative (dès sept. 2026)': 'Cumulative cash (from Sept. 2026)',

    # ------------------------------------------------------------------ bilan
    'LASCLAY-Bilan ($CDN)': 'LASCLAY — Balance sheet (CAD)',
    'Actif à court terme': 'Current assets',
    'Encaisse': 'Cash',
    'Comptes à recevoir (CAR)': 'Accounts receivable (AR)',
    'Subventions à recevoir': 'Grants receivable',
    "Crédits d'impôt à recevoir": 'Tax credits receivable',
    'Inventaire Matières premières': 'Raw materials inventory',
    'Inventaire PEC': 'Work-in-process inventory',
    'Inventaire Produits finis': 'Finished goods inventory',
    'Inventaire MP': 'Raw materials inventory',
    'Inventaire PF': 'Finished goods inventory',
    'Actif de stock': 'Inventory assets',
    "Total de l'actif à court terme": 'Total current assets',
    'Actif à long terme': 'Long-term assets',
    'Équipements': 'Equipment',
    'Amélioration locative': 'Leasehold improvements',
    'Matériel informatique': 'Computer equipment',
    'Matériel Roulant': 'Rolling stock',

    # ------------------------------------------------------------------ immos
    'Immobilisations 2025-2026-27-28': 'Capital assets 2025-2026-27-28',
    'Immobilisations 2026-2027': 'Capital assets 2026-2027',
    'Immobilisations 2027-2028': 'Capital assets 2027-2028',
    'Immobilisations 2028-2029': 'Capital assets 2028-2029',
    'Coût': 'Cost',
    'Acquisitions': 'Additions',
    'Dispositions': 'Disposals',
    'Coût à la fin': 'Closing cost',
    'AMT cumulé': 'Accumulated depreciation',
    'Amortissement': 'Depreciation',
    'Disposition': 'Disposal',
    'AMT Cumulé à la fin': 'Closing accumulated depreciation',
    'Méthode AMT': 'Depreciation method',
}

GLOSSAIRE = {**{s: s for s in IDENTIQUE}, **TRADUIT}
