# -*- coding: utf-8 -*-
"""Glossaire du chiffrier, partie F — le journal d'audit.

C'est la deuxième feuille du classeur et la première qu'un analyste ouvre. Elle
raconte ce que la révision a corrigé et ce qui reste à valider.
"""

IDENTIQUE = []

TRADUIT = {
    'JOURNAL D’AUDIT DU MODÈLE — 30 juillet 2026':
        'MODEL AUDIT LOG — 30 July 2026',
    'Ce que la révision a corrigé, et ce qui reste à valider avant de déposer le dossier.':
        'What the revision corrected, and what remains to be confirmed before the file is submitted.',
    'A. INTÉGRITÉ TECHNIQUE': 'A. TECHNICAL INTEGRITY',
    'B. FOND': 'B. SUBSTANCE',
    'C. CE QUI RESTE À VALIDER AVANT DE DÉPOSER':
        'C. WHAT REMAINS TO BE CONFIRMED BEFORE SUBMISSION',

    "• Account Recevables N6 contenait le littéral #REF! : c'était la racine des erreurs du budget de caisse. Réparé, et le bloc 2024-2025 repointé sur « Résultats2025maj » (il lisait des colonnes mortes de « Résultats2024 »).":
        '• Accounts Receivable N6 contained the literal #REF!: this was the root of the cash budget errors. Repaired, and the 2024-2025 block re-pointed at “Résultats2025maj” (it was reading dead columns of “Résultats2024”).',
    '• Deux liens externes morts (« xlPathMissing ») retirés : ils faisaient afficher « mettre à jour les liens ? » à chaque ouverture et bloquaient le recalcul.':
        '• Two dead external links (“xlPathMissing”) removed: they triggered the “update links?” prompt on every open and blocked recalculation.',
    "• 33 351 formules partagées développées en formules autonomes. Un groupe (RSDE matériaux, 2026-2027) n'avait plus de formule maîtresse : 8 cellules ne calculaient rien.":
        '• 33,351 shared formulas expanded into standalone formulas. One group (SR&ED materials, 2026-2027) had lost its master formula: 8 cells were computing nothing.',
    '• 4 517 SUMIF portaient sur des colonnes entières (A:A) des feuilles de collage QuickBooks. Ramenés aux 400 premières lignes : même résultat, recalcul possible.':
        '• 4,517 SUMIFs ran over whole columns (A:A) of the QuickBooks paste sheets. Narrowed to the first 400 rows: same result, recalculation now possible.',
    "• Ligne 181 du résultat : 27 colonnes sur 48 omettaient la ligne 180 (avance de l'actionnaire) dans le total du financement.":
        '• Income statement row 181: 27 of the 48 columns omitted row 180 (shareholder advance) from the financing total.',
    "• EBITDA : l'ancienne formule rajoutait les impôts à un résultat déjà avant impôts, et n'ajoutait que quatre des sept lignes d'intérêts. Redéfini.":
        '• EBITDA: the old formula added back tax to a result already stated before tax, and added back only four of the seven interest lines. Redefined.',
    '• Le total annuel du budget de caisse sommait la colonne au lieu des douze mois : quatre exercices perdaient un montant inscrit directement dans un mois (-30 467 $, -49 974 $, -39 317 $, -107 367 $).':
        '• The cash budget’s annual total summed the column instead of the twelve months: four fiscal years lost an amount entered directly in a month (−$30,467, −$49,974, −$39,317, −$107,367).',
    "• Bilan : l'inventaire de matières lisait mars-août 2025 au lieu de mars-août 2026 ; l'emprunt Shopify redémarrait à janvier 2027 en mars 2027 ; « Passif à long terme » excluait la nouvelle dette (125 000 $ d'écart affiché sur la même page).":
        '• Balance sheet: materials inventory was reading March-August 2025 instead of March-August 2026; the Shopify loan restarted at January 2027 in March 2027; “Long-term liabilities” excluded the new debt ($125,000 of discrepancy shown on the same page).',
    "• Dette à long terme : les soldes d'ouverture de septembre 2025 manquaient pour le prêt BDC FDR et le BDC 18K, ce qui affichait des dettes NÉGATIVES (-18 337 $ et -3 000 $). Trois rustines codées en dur ont été retirées.":
        '• Long-term debt: the September 2025 opening balances were missing for the BDC working capital loan and the BDC 18K, which showed NEGATIVE debt (−$18,337 and −$3,000). Three hardcoded patches were removed.',
    "• Ventes prévisionnelles : le prix des casquettes prenait celui des boucles d'oreilles ; trois produits 2027-2028 prenaient le prix de la crème contour des yeux ; les mitaines appliquaient la croissance 2027-2028 à la base 2025-2026 ; le total 2025-2026 n'additionnait que 53 des 76 lignes de revenu ; trois produits n'avaient pas de mois d'août.":
        '• Sales forecast: the price of caps was taking that of the earrings; three 2027-2028 products were taking the price of the eye cream; mittens applied 2027-2028 growth to the 2025-2026 base; the 2025-2026 total added only 53 of the 76 revenue rows; three products had no August.',
    "• Les parts mensuelles de saisonnalité étaient divisées par un total saisi à la main qui ne valait pas la somme des douze mois : jusqu'à +15 % de revenu fantôme par produit.":
        '• The monthly seasonality shares were divided by a hand-entered total that did not equal the sum of the twelve months: up to +15% of phantom revenue per product.',
    '• Hypothèses saisies à 8 et 3,5 au lieu de 0,08 et 0,035 (escompte et frais Shopify des exercices 2027-2029) ; bloc de brouillon contenant une cellule à 47,7 M$ supprimé.':
        '• Assumptions entered as 8 and 3.5 instead of 0.08 and 0.035 (discount and Shopify fees for 2027-2029); a scratch block containing a $47.7M cell deleted.',
    "• Le bilan ne balançait pas : -18 732 $ à août 2026 et -108 402 $ à août 2027. Il balance maintenant à zéro sur les 48 mois, parce qu'il n'y a plus qu'une seule chaîne de trésorerie au lieu de deux prévisions parallèles non réconciliées.":
        '• The balance sheet did not balance: −$18,732 at August 2026 and −$108,402 at August 2027. It now balances to zero across all 48 months, because there is a single cash chain instead of two unreconciled parallel forecasts.',

    '• Trajectoire de ventes : le modèle prévoyait +59 % en 2026-2027 et +84 % en 2027-2028. Les quantités annuelles des 76 produits ont été remises sur les unités réellement vendues chez Shopify entre septembre 2025 et juillet 2026, puis crues par catégorie. Résultat : +28,6 %, +18,4 %, +17,7 %.':
        '• Sales trajectory: the model forecast +59% in 2026-2027 and +84% in 2027-2028. The annual quantities of all 76 products were reset on units actually sold in Shopify between September 2025 and July 2026, then grown by category. Result: +28.6%, +18.4%, +17.7%.',
    "• Horticole : le modèle portait 340 203 $ en 2025-2026 et projetait 1 084 353 $ en 2027-2028. Le réel Shopify est 108 187 $ (bombes semencières : 1 087 unités, pas 10 000). L'asclépiade est vivace, le marché sature : croissance ramenée à zéro.":
        '• Horticulture: the model carried $340,203 in 2025-2026 and projected $1,084,353 in 2027-2028. The Shopify actual is $108,187 (seed bombs: 1,087 units, not 10,000). Milkweed is a perennial and the market saturates: growth brought down to zero.',
    "• Coût des marchandises : le modèle bâtissait le CMV sur les coûts unitaires cibles des fiches Tunisie, ce qui donnait 17,4 % de CMV et 82 % de marge en 2026-2027 — au-dessus du meilleur exercice jamais réalisé. Ramené à des ratios calibrés sur trois exercices, avec l'amélioration du virage manufacturier énoncée dans Inputs lignes 56 à 61.":
        '• Cost of goods: the model built COGS on the target unit costs from the Tunisia sheets, which gave 17.4% COGS and 82% margin in 2026-2027 — above the best year ever achieved. Brought back to ratios calibrated on three fiscal years, with the manufacturing-pivot improvement set out in Inputs rows 56 to 61.',
    "• Sous-traitance d'assemblage : elle baissait de 37 % pendant que les ventes montaient. Elle suit maintenant le volume.":
        '• Assembly subcontracting: it fell 37% while sales rose. It now follows volume.',
    "• Plan d'embauche : trois postes démarraient le 1er septembre 2026 (+169 % de masse salariale). Il en reste un en 2026-2027 (gestion logistique, 1er octobre) et un en 2027-2028 (marketing, 1er janvier). Le poste de service client est retiré : la boîte support est automatisée. Hausses salariales ramenées de 10 % à 3 % par an.":
        '• Hiring plan: three positions started on 1 September 2026 (+169% payroll). One remains in 2026-2027 (logistics management, 1 October) and one in 2027-2028 (marketing, 1 January). The customer-service position is removed: the support inbox is automated. Salary increases brought down from 10% to 3% a year.',
    "• PARI-CNRC : 75 000 $ étaient inscrits en revenu 2026-2027 alors que la demande n'est pas déposée. Retiré du scénario de base.":
        '• NRC-IRAP: $75,000 was booked as 2026-2027 revenue although the application has not been filed. Removed from the base scenario.',
    "• « Économies d'optimisation » (11 200 $ à 17 400 $ par an) étaient comptabilisées en revenu. Une économie de coût n'est pas un revenu : retirée.":
        '• “Optimisation savings” ($11,200 to $17,400 a year) were booked as revenue. A cost saving is not revenue: removed.',
    '• Avance de l’actionnaire : entente de juillet 2026 — 80 000 $ avancés le 15 août 2026, remboursables sur 12 mois à 8 % (capital égal de 6 666,67 $ de septembre 2026 à août 2027, 3 733 $ d’intérêt au total). Le modèle la portait à 75 000 $ postposée, sans intérêt ni remboursement : les trois hypothèses sont remplacées. Paramètres dans Inputs, rangées 115 à 119 ; échéancier dans « Dette à long terme », rangées 46, 51 et 53.':
        '• Shareholder advance: July 2026 agreement — $80,000 advanced on 15 August 2026, repayable over 12 months at 8% (equal principal of $6,666.67 from September 2026 to August 2027, $3,733 of interest in total). The model carried it at $75,000, subordinated, with no interest and no repayment: all three assumptions are replaced. Parameters in Inputs, rows 115 to 119; schedule in “Long-term debt”, rows 46, 51 and 53.',
    '• Dividende de 5 % du bénéfice net : retiré pendant le terme des prêts.':
        '• A 5% dividend on net profit: removed for the term of the loans.',
    "• Prêt BDC de 125 000 $ : il était remboursé d'un coup en décembre 2027. Remplacé par une facilité de 460 000 $ amortie sur 60 mois qui solde le capital marchand.":
        '• The $125,000 BDC loan: it was repaid in a single instalment in December 2027. Replaced by a $460,000 facility amortised over 60 months that pays off the merchant capital.',
    "• Disposition d'équipements : le résultat portait la valeur nette comptable complète (39 670 $) en perte. La perte réelle est 4 491 $ (VNC 39 670 − produit 33 979 − gain de 1 200 $ sur les rackings) et l'encaissement de 35 179 $ figure aux investissements.":
        '• Equipment disposal: the income statement carried the full net book value ($39,670) as a loss. The actual loss is $4,491 (NBV $39,670 − proceeds $33,979 − a $1,200 gain on the racking) and the $35,179 of proceeds appears under investing.',
    "• Amortissement : QuickBooks n'en avait passé aucun de l'exercice. La régularisation d'août reprend le registre d'immobilisations, et le bilan suit désormais exactement l'amortissement du résultat.":
        '• Depreciation: QuickBooks had recorded none for the year. The August adjustment takes the capital asset register, and the balance sheet now follows the income statement’s depreciation exactly.',
    "• RSDE 2025-2026 : la cellule forçait le total à 99 000 $ (formule = -99000-SUM(...)). Remplacée par la même méthode que 2026-2027, tirée des salaires admissibles.":
        '• SR&ED 2025-2026: the cell forced the total to $99,000 (formula = -99000-SUM(...)). Replaced by the same method as 2026-2027, derived from eligible salaries.',
    "• Une ligne « hors aides publiques » a été ajoutée au résultat (lignes 141 et 144) : l'analyste la calculera de toute façon, autant la lui donner.":
        '• An “excluding public funding” line was added to the income statement (rows 141 and 144): the analyst will compute it anyway, so it may as well be given.',

    "• Le bilan réel de QuickBooks s'arrête à février 2026 alors que le résultat réel va jusqu'à juin 2026. Coller quatre mois de bilan de plus dans « QBOBS à maj » (colonnes AI et suivantes) avant de déposer : la prévision de trésorerie s'ancre sur le dernier mois de bilan réel.":
        '• The actual QuickBooks balance sheet stops at February 2026 while the actual income statement runs to June 2026. Paste four more months of balance sheet into “QBOBS to update” (columns AI onward) before submission: the cash forecast anchors on the last actual balance sheet month.',
    '• Solde bancaire : le modèle donne 38 515 $ au 31 août 2026 ; le solde mesuré au 31 juillet était 28 472 $ et QuickBooks affiche 30 551 $ au compte chèques plus 6 346 $ PayPal. Reconcilier avec AccèsD (Budget de caisse, lignes 38 à 40).':
        '• Bank balance: the model gives $38,515 at 31 August 2026; the measured balance at 31 July was $28,472 and QuickBooks shows $30,551 in the chequing account plus $6,346 in PayPal. Reconcile with AccèsD (Cash budget, rows 38 to 40).',
    "• Vente d'équipements : les dépôts sont encore dans la file « À réviser » de QuickBooks. Faire trancher par le comptable la question des taxes (si le prix de 33 979 $ est réputé les inclure, environ 4 426 $ sont à remettre) et faire passer les écritures.":
        '• Equipment sale: the deposits are still in the QuickBooks “For review” queue. Have the accountant settle the sales-tax question (if the $33,979 price is deemed to include them, about $4,426 is remittable) and post the entries.',
    '• Avance de l’actionnaire : QuickBooks n’en enregistre que 5 000 $ au 30 juin 2026. Les 80 000 $ de l’entente du 15 août 2026 doivent être documentés (contrat, taux, échéancier) avant le dépôt — un prêteur à terme demandera aussi une convention de postposition, qui suspendrait l’échéancier de 12 mois.':
        '• Shareholder advance: QuickBooks records only $5,000 of it at 30 June 2026. The $80,000 from the 15 August 2026 agreement must be documented (contract, rate, schedule) before submission — a term lender will also require a subordination agreement, which would suspend the 12-month schedule.',
    "• Pertes fiscales reportables : 151 649 $ (Inputs C43) reste un estimé du comptable, à confirmer. Le calcul d'impôt s'en sert pour la régularisation de fin d'exercice.":
        '• Loss carryforwards: $151,649 (Inputs C43) remains an accountant’s estimate, to be confirmed. The tax calculation uses it for the year-end adjustment.',
    "• Publicité numérique : 22 % du revenu brut en 2026-2027. Un analyste demandera le coût d'acquisition et la valeur à vie d'un client. Les avoir sous la main.":
        '• Digital advertising: 22% of gross revenue in 2026-2027. An analyst will ask for customer acquisition cost and lifetime value. Have them to hand.',
    "• Trois produits vendus en 2025-2026 ne sont pas dans le modèle (chandail polaire, gants magiques, mitaines en cuir de mouton, environ 21 000 $). Ils sont dans la ligne « produits hors catalogue modélisé ». À modéliser s'ils deviennent significatifs.":
        '• Three products sold in 2025-2026 are not in the model (fleece sweater, magic gloves, sheepskin mittens, about $21,000). They sit in the “products outside the modelled catalogue” row. To be modelled if they become significant.',
    '• Le prêt Accord D, les prêts privés et le BDC 11K sont projetés à partir de leurs échéanciers ; vérifier les soldes réels au 31 août 2026 avant dépôt.':
        '• The Accord D loan, the private loans and the BDC 11K are projected from their schedules; check the actual balances at 31 August 2026 before submission.',
    '• RÉGLÉ le 30 juillet : le bilan réel de QuickBooks a été tiré par le proxy finance et collé sur les douze mois de 2025-2026 (« QBOBS à maj », colonnes AC à AN). Le bilan du modèle porte maintenant dix mois réels, sept. 2025 à juin 2026, aligné sur le résultat. Juillet et août restent prévisionnels : la colonne juillet de QuickBooks est une photo du mois en cours.':
        '• SETTLED 30 July: the actual QuickBooks balance sheet was pulled through the finance proxy and pasted across the twelve months of 2025-2026 (“QBOBS to update”, columns AC to AN). The model’s balance sheet now carries ten actual months, Sept. 2025 to June 2026, aligned with the income statement. July and August remain forecast: the QuickBooks July column is a snapshot of the month in progress.',
    '• RÉGLÉ : l’ancrage de trésorerie codé en dur (28 472 $) est remplacé par l’encaisse réelle de QuickBooks au 30 juin 2026, soit -5 284 $ (compte chèques -11 635 $, PayPal 6 346 $, parts 5 $), avec la marge EDC tirée à 83 551 $. Le compte chèques a été corrigé de -8 000 $ à la séance de tenue de livres du 30 juillet : le creux réel de juin est donc négatif.':
        '• SETTLED: the hardcoded cash anchor ($28,472) is replaced by the actual QuickBooks cash at 30 June 2026, that is −$5,284 (chequing −$11,635, PayPal $6,346, shares $5), with the EDC line drawn at $83,551. The chequing account was corrected by −$8,000 at the 30 July bookkeeping session: June’s actual trough is therefore negative.',
    '• Le mappage des comptes (qbo_mapping.json) portait cinq défauts qui faisaient disparaître des soldes réels : la clé du prêt BDC 100K était malformée (54 266 $ au 30 juin ne tombaient nulle part), le BDC 11K, le prêt AccordD 003, la carte de crédit expédition et le compte parent « Prêts des actionnaires » (5 000 $, l’avance réellement enregistrée) n’étaient pas mappés, et le compte 1650 « Intérêts Merchant Growth » était classé en immobilisations.':
        '• The account mapping (qbo_mapping.json) carried five defects that made real balances disappear: the BDC 100K loan key was malformed ($54,266 at 30 June landed nowhere), the BDC 11K, the Accord D 003 loan, the shipping credit card and the parent account “Shareholder loans” ($5,000, the advance actually recorded) were unmapped, and account 1650 “Merchant Growth interest” was classified as a capital asset.',
    '• Vérifié : les SUMIF du bilan captent maintenant l’intégralité du bilan QuickBooks, au cent près, sur les douze mois. Le compte 1650 figurait sur deux rangées de la feuille de collage (18 712 $ comptés en double) ; la rangée en trop est vidée.':
        '• Verified: the balance sheet SUMIFs now capture the entire QuickBooks balance sheet, to the cent, across the twelve months. Account 1650 appeared on two rows of the paste sheet ($18,712 double-counted); the extra row has been cleared.',
    '• Reste à valider : la vente d’équipements est toujours dans « À réviser » ; le contrat de l’avance de 80 000 $ du 15 août 2026 reste à signer ; les pertes fiscales reportables (151 649 $) restent un estimé du comptable ; les soldes réels des prêts Accord D, privés et BDC 11K au 31 août 2026 sont à confirmer.':
        '• Still to confirm: the equipment sale is still in “For review”; the contract for the $80,000 advance of 15 August 2026 remains to be signed; the loss carryforwards ($151,649) remain an accountant’s estimate; the actual balances of the Accord D, private and BDC 11K loans at 31 August 2026 are to be confirmed.',
    '• Ajouté le 30 juillet : coût d’acquisition et valeur à vie d’un client, calculés sur le réel Shopify et QuickBooks (sommaire section 7) ; ratios de crédit dont la couverture du service de la dette (section 8) ; liquidité réelle au moment de la demande (section 9). Les 360 hypothèses d’exploitation encore tapées mois par mois dans les blocs de prévision remontent dans Inputs à partir de la ligne 100.':
        '• Added 30 July: customer acquisition cost and lifetime value, computed on Shopify and QuickBooks actuals (summary section 7); credit ratios including debt service coverage (section 8); actual liquidity at the time of the request (section 9). The 360 operating assumptions still typed month by month in the forecast blocks are moved up into Inputs from row 100.',
    '• Canal détail (consignation au Canada) ajouté au modèle : pilotes dans Inputs rangées 121 à 138, revenu au résultat rangée 12, points de vente rangée 13, stock en consignation isolé au bilan rangée 84. Les escomptes, le transport au consommateur et la publicité restent calculés sur le commerce en ligne seul.':
        '• Retail channel (consignment across Canada) added to the model: drivers in Inputs rows 121 to 138, revenue on income statement row 12, points of sale on row 13, consignment inventory isolated on balance sheet row 84. Discounts, consumer shipping and advertising remain computed on e-commerce alone.',
    '• La bascule Inputs!C70 porte désormais deux scénarios : 1 = conservateur réaliste (bailleurs institutionnels), 2 = ambitieux (investisseur privé). Les anciennes valeurs du scénario prudent sont conservées en colonne F d’Inputs comme sensibilité baissière, non branchée.':
        '• The Inputs!C70 switch now carries two scenarios: 1 = realistic conservative (institutional lenders), 2 = ambitious (private investor). The former cautious-scenario values are kept in Inputs column F as a downside sensitivity, not wired in.',
    "• Canal détail refait ville par ville : 40 villes (les 20 plus grandes du Québec, les 25 plus grandes du Canada), 109 points de vente possibles, un indice d'affinité tiré des ventes en ligne par habitant. Les Défricheuses, détaillant exclusif à Montréal, donnent le calage : 13 801 $ encaissés de septembre 2025 à juin 2026. Feuille « Détail par ville » ; elle pilote les rangées 123 à 125 et 139 à 141 d'Inputs.":
        '• Retail channel rebuilt city by city: 40 cities (the 20 largest in Quebec, the 25 largest in Canada), 109 possible points of sale, an affinity index drawn from online sales per capita. Les Défricheuses, the exclusive retailer in Montreal, provides the calibration: $13,801 collected from September 2025 to June 2026. Sheet “Retail by city”; it drives Inputs rows 123 to 125 and 139 to 141.',
    "• 2025-2026 ne montrait aucune vente au détail alors qu'il y en avait. Les 13 801 $ des Défricheuses sont reclassés du B2B vers le canal détail, sans changer le total de l'exercice clos.":
        '• 2025-2026 showed no retail sales when there were some. The $13,801 from Les Défricheuses is reclassified from B2B to the retail channel, without changing the closed year’s total.',
    "• Taxes à payer : onze des douze mois de 2028-2029 lisaient la rangée 34, « Frais courus à payer », au lieu de la 35. Le facteur de croissance écrit en dur (1,35 puis 1,4) devient le rapport des ventes nettes d'un exercice à l'autre, juste dans les deux scénarios.":
        '• Sales tax payable: eleven of the twelve months of 2028-2029 were reading row 34, “Accrued liabilities”, instead of row 35. The hardcoded growth factor (1.35 then 1.4) becomes the ratio of net sales from one year to the next, correct in both scenarios.',
    "• Calendrier des taxes posé tel qu'il est déclaré : TVQ au mois, TPS à l'année avec un solde dû le 30 novembre. Le solde du bilan se construit par ses mouvements à partir d'août 2026 au lieu de recopier un profil.":
        '• Sales-tax calendar set as it is actually filed: QST monthly, GST annually with a balance due 30 November. The balance sheet figure is built from its movements starting in August 2026 instead of copying a profile.',
    "• Les taux de taxe viennent des vrais montants de 2025-2026, du 1er septembre 2025 au 30 juillet 2026 : 46 457 $ de TPS/TVH perçue chez Shopify (part fédérale calculée région par région), 2 619 $ sur les factures QuickBooks, 32 469 $ de CTI. La TPS nette de 2025-2026 vaut 13 910 $, payable le 30 novembre 2026, puis 28 721 $ et 48 510 $.":
        '• The tax rates come from the actual 2025-2026 amounts, 1 September 2025 to 30 July 2026: $46,457 of GST/HST collected in Shopify (federal share computed region by region), $2,619 on QuickBooks invoices, $32,469 of input tax credits. Net GST for 2025-2026 is $13,910, payable 30 November 2026, then $28,721 and $48,510.',
    "• La TPS perçue vaut 5,0011 % des ventes nettes et la TVQ 8,3851 %, au-dessus du taux nominal sur la part canadienne : la taxe porte sur les ventes brutes et sur le transport. La base de RTI (47,17 %) est distincte de la base de CTI (52,58 %) : une partie des achats se fait hors du Québec. Ces crédits baissent quand la couture quitte le Québec.":
        '• GST collected is 5.0011% of net sales and QST 8.3851%, above the nominal rate on the Canadian share: the tax applies to gross sales and to shipping. The QST input base (47.17%) is distinct from the GST input base (52.58%): part of the purchasing happens outside Quebec. Those credits fall as sewing leaves Quebec.',
    "• Finitions du 30 juillet : les étiquettes « FY20xx » passent au gabarit « 2026-2027 » ; les descriptions de scénario d'Inputs A71 et A72 sont maintenant construites par formule sur les rangées qu'elles décrivent, après avoir annoncé des déploiements qui ne correspondaient plus ; les rangées ajoutées reçoivent un format ; la limite de la marge de crédit et le contrôle du tirage sont posés à la rangée 163 d'Inputs.":
        '• Finishing touches, 30 July: the “FY20xx” labels move to the “2026-2027” pattern; the scenario descriptions in Inputs A71 and A72 are now regenerated from the rows they describe, after announcing rollouts that no longer matched; the added rows receive a number format; the line of credit limit and the draw control are set on Inputs row 163.',
    "• Reste à valider avant le dépôt : la vente d'équipements est toujours dans « À réviser » chez QuickBooks ; le contrat de l'avance de 80 000 $ du 15 août 2026 reste à signer ; les pertes fiscales reportables (151 649 $) restent un estimé du comptable ; les soldes réels des prêts Accord D, privés et BDC 11K au 31 août 2026 sont à confirmer ; juillet et août 2026 restent prévisionnels, mais juillet tombe à 41 $ près du réel Shopify.":
        '• Still to confirm before submission: the equipment sale is still in QuickBooks “For review”; the contract for the $80,000 advance of 15 August 2026 remains to be signed; the loss carryforwards ($151,649) remain an accountant’s estimate; the actual balances of the Accord D, private and BDC 11K loans at 31 August 2026 are to be confirmed; July and August 2026 remain forecast, but July lands within $41 of the Shopify actual.',
    '• Séance de tenue de livres du 30 juillet, rapatriée par fix_aq.py. Juillet 2026 est maintenant comptabilisé chez QuickBooks : 3 117 $ de revenus, 7 579 $ de coût des marchandises, 43 986 $ de dépenses, soit une perte de 47 758 $. Le modèle porte encore juillet en prévision, à -39 272 $ : il est optimiste de 8 486 $ sur ce mois-là.':
        '• Bookkeeping session of 30 July, brought in by fix_aq.py. July 2026 is now recorded in QuickBooks: $3,117 of revenue, $7,579 of cost of goods, $43,986 of expenses, a loss of $47,758. The model still carries July as a forecast, at −$39,272: it is $8,486 optimistic on that month.',
    '• Une vente corporative de 8 000 $ d’avril 2026 a été retirée des livres, avec sa contrepartie au compte chèques. Les ventes nettes de 2025-2026 passent à 978 383 $ et le résultat avant impôts à -97 283 $. L’encaisse d’avril tombe à -71 $ et celle de juin à -5 284 $.':
        '• An $8,000 corporate sale from April 2026 was removed from the books, along with its counterpart in the chequing account. Net sales for 2025-2026 fall to $978,383 and the pre-tax result to −$97,283. April cash falls to −$71 and June cash to −$5,284.',
    '• Autres reclassements de la séance : 1 281 $ de sous-traitance de couture retirés de janvier ; les frais de RSDE déplacés de « Sous-traitance » vers « Matériaux » et étalés sur les mois où ils ont été engagés ; 4 718 $ de décembre passés de « RSDE - Matériaux » à « RSDE - Salaires Design » ; 277 $ d’intérêts AccordD ajoutés en février.':
        '• Other reclassifications from the session: $1,281 of sewing subcontracting removed from January; the SR&ED costs moved from “Subcontracting” to “Materials” and spread over the months in which they were incurred; $4,718 from December moved from “SR&ED — materials” to “SR&ED — design salaries”; $277 of Accord D interest added in February.',
    '• Les feuilles de collage sont désormais recollées par libellé et non par position. Le numéro de compte ne suffit pas : « Bénéfices non répartis » et « Bénéfice de l’année » n’en ont pas, et ce sont eux qui portent la contrepartie de toute correction au résultat. Les oublier sortait le bilan de l’équilibre du montant exact de la correction.':
        '• The paste sheets are now refreshed by label rather than by position. The account number is not enough: “Retained earnings” and “Profit for the year” do not have one, and they are what carry the counterpart of any correction to the income statement. Missing them threw the balance sheet out by exactly the amount of the correction.',
}

GLOSSAIRE = {**{s: s for s in IDENTIQUE}, **TRADUIT}
