# -*- coding: utf-8 -*-
"""Glossaire du chiffrier, partie B — bilan, dette, comptes QuickBooks, mois.

Les libellés de compte QuickBooks gardent leur numéro : c'est lui qui fait le
lien avec le grand livre, et un prêteur qui compare les deux fichiers doit
retrouver le même compte des deux côtés.
"""

IDENTIQUE = [
    'VNC', 'Dégressif', 'Merchant Growth Capital', 'Merchant growth',
    'BDC FDR', 'BDC FDR #2', 'BDC FDR #3', 'Prêt Phil', 'Prêt Phil #2',
    'Amazon', 'Tonitex', 'Ex works', 'Asclépiade', 'Pur soyer',
    'West coast seeds + Akene', 'Everwilde', 'Fibra', 'Alibaba', 'ZI DAI',
    'REVENUS', 'ACTIFS', 'Total',
]

TRADUIT = {
    # --------------------------------------------------------- immobilisations
    'Taux': 'Rate',
    'Propriété intellectuelle': 'Intellectual property',
    'Véhicule': 'Vehicle',
    'Véhicules': 'Vehicles',
    'Linéaire 8 ans': 'Straight-line, 8 years',
    'Linéaire 6 ans': 'Straight-line, 6 years',
    '(durée bail+ 1 option)': '(lease term + 1 option)',
    'Améliorations locatives': 'Leasehold improvements',
    'Acquisitions :': 'Additions:',
    'total Immos': 'Total capital assets',
    'Amortissement mensuel': 'Monthly depreciation',

    # ------------------------------------------------------------------ bilan
    "Total de l'actif à long terme": 'Total long-term assets',
    "Total de l'actif": 'Total assets',
    'Passif à court terme': 'Current liabilities',
    'Marges de crédit': 'Lines of credit',
    'Comptes à payer (CAP)': 'Accounts payable (AP)',
    'Salaires et vacances à payer': 'Salaries and vacation payable',
    'Portion CT de la dette à LT': 'Current portion of long-term debt',
    'Total du passif à court terme': 'Total current liabilities',
    'Passif à long terme': 'Long-term liabilities',
    'Total du passif à long terme': 'Total long-term liabilities',
    'Total du passif': 'Total liabilities',
    'Capitaux propres': 'Equity',
    'Capital-actions': 'Share capital',
    'Bénéfices non répartis (déficit)': 'Retained earnings (deficit)',
    "Bénéfice de l'année (perte)": 'Profit for the year (loss)',
    'Total des capitaux propres': 'Total equity',
    'Total du passif et des capitaux propres': 'Total liabilities and equity',
    'Fond de roulement': 'Working capital',
    'Comptes payables à la fin': 'Closing accounts payable',

    # -------------------------------------------------------------- la dette
    'Dette à long terme': 'Long-term debt',
    'Prêt BDC 11K': 'BDC 11K loan',
    'Prêt BDC 18K': 'BDC 18K loan',
    'Prêt BDC 10K': 'BDC 10K loan',
    'Prêt BDC FDR': 'BDC working capital loan',
    'Prêt accord D 001': 'Accord D loan 001',
    'Prêt accord D 002': 'Accord D loan 002',
    'Prêt accord D 003': 'Accord D loan 003',
    'Prêt accord D 004': 'Accord D loan 004',
    'Prêt privé #2': 'Private loan #2',
    'Prêt privé Phil': 'Phil private loan',
    'Prêt privé Phil #2': 'Phil private loan #2',
    'Solde prêt accord d': 'Accord D loan balance',
    'Solde BDC': 'BDC balance',
    'Solde BDC 18K': 'BDC 18K balance',
    'Solde BDC 10K': 'BDC 10K balance',
    'Solde BDC 11K': 'BDC 11K balance',
    'Solde Shopify': 'Shopify balance',
    'Solde Shopify2': 'Shopify balance 2',
    'Solde au 31 août 2024': 'Balance at 31 August 2024',
    'Solde au 31 août 2025': 'Balance at 31 August 2025',
    'Sold au 31 août 2029': 'Balance at 31 August 2029',
    'Emprunt Shopify 3': 'Shopify loan 3',
    'Emprunt Shopify 4': 'Shopify loan 4',
    'Remboursements de capital': 'Principal repayments',
    'Total intérêts dette long terme': 'Total long-term debt interest',
    'Intérêts BDC 11K (capital reporté)': 'BDC 11K interest (principal deferred)',
    'BDC 11K (capital dès nov. 2026)': 'BDC 11K (principal from Nov. 2026)',
    '(moratoire 6 mois)': '(6-month moratorium)',
    'Solde intérêt': 'Interest balance',
    'Service de la dette': 'Debt service',
    'Marge de crédit Desj': 'Desjardins line of credit',
    'Dette totale': 'Total debt',
    'Nouvelle dette :': 'New debt:',

    # ------------------------------------------------------------- achats
    'Hypothèses des déboursés:': 'Disbursement assumptions:',
    'Toutes les dépenses sont payées le mois courants sauf :':
        'All expenses are paid in the current month except:',
    'Inventaire de début-MP Produits finis':
        'Opening inventory — materials and finished goods',
    'Achat de produit': 'Product purchases',
    'Matière': 'Material',
    'Termes': 'Terms',
    'Terme': 'Term',
    'Fournisseur': 'Supplier',
    'Sur réception': 'On receipt',
    'Graines asclépiade commune': 'Common milkweed seed',
    'Graines plantes variées (bombes)': 'Assorted plant seed (seed bombs)',
    'Prépaiement': 'Prepayment',
    'Tissus variés': 'Assorted fabrics',
    'Asie': 'Asia',
    'Filament impression 3D': '3D printing filament',
    'Sous-total': 'Subtotal',
    'Transport et douanes': 'Freight and customs',
    'Total achats': 'Total purchases',
    'Moins :COGS WEB': 'Less: COGS — web',
    'Moins : COGS B2B': 'Less: COGS — B2B',
    'Inventaire de fin': 'Closing inventory',
    "Variation d'inventaire": 'Change in inventory',
    "Ratio d'inventaire": 'Inventory ratio',
    'Asclépiade (Eko-Terre, Fibra)': 'Milkweed (Eko-Terre, Fibra)',
    'Graines (Everwilde)': 'Seed (Everwilde)',
    'Bombes semencières': 'Seed bombs',
    'Tissus et composants Chine (Alibaba, ZI DAI...)':
        'Fabrics and components from China (Alibaba, ZI DAI…)',
    'Filament / divers': 'Filament / miscellaneous',
    'Courbe saisonnière des achats (part du budget annuel; avance 3-4 mois: 50% mai-août, 20% sep-oct)':
        'Seasonal purchase curve (share of annual budget; 3-4 months ahead: 50% May-Aug, 20% Sep-Oct)',
    'PO Vegeto Eko-Terre 91 400$ (20260417-1): factures juil/oct/jan intégrées ligne 20; paiements réels août/déc/mars via Budget de caisse ligne 29':
        'Vegeto Eko-Terre PO $91,400 (20260417-1): invoices Jul/Oct/Jan on line 20; actual payments Aug/Dec/Mar via Cash budget line 29',
    'Calibration retirée (B52=1): taux réels par produit (fiches A26 + plan BMB) désormais dans Ventes prévisionnelles; ligne 497 = BMB (x1.26 douane+bateau au P&L), ligne 498 = sous-traitance QC/collabs sans douane':
        'Calibration removed (B52=1): actual per-product rates (A26 sheets + BMB plan) now in Sales forecast; line 497 = BMB (×1.26 customs + sea freight in the P&L), line 498 = QC subcontracting / collaborations with no customs',

    # --------------------------------------------------------- en-têtes divers
    'LASCLAY-Résultats année en cours': 'LASCLAY — Income statement, current year',
    "Pour l'exercice se terminant le 31 AOÛT 2026-2027-2028":
        'For the fiscal years ending 31 AUGUST 2026-2027-2028',
    'Ventes:': 'Sales:',
    'Total des ventes': 'Total sales',
    'Croissance': 'Growth',
    'Quantité': 'Quantity',
    'Prix': 'Price',
    'QTÉ ANN.': 'ANNUAL QTY',
    '2023 qté réel': '2023 actual qty',
    '2024 qté réel': '2024 actual qty',
    '% réel mensuel': '% actual, monthly',
    'Produits hiver:': 'Winter products:',
    'acc. hiver': 'winter acc.',
    'Mitaines': 'Mittens',
    'Foulards': 'Scarves',
    'Cache cou': 'Neck warmer',
    '1592,01/semaine': '1,592.01 / week',

    # ------------------------------------------------------------------ mois
    'Mai': 'May', 'Juin': 'June', 'Août': 'August', 'Aout': 'August',
    'Septembre': 'September', 'Octobre': 'October', 'Novembre': 'November',
    'Décembre': 'December', 'Février': 'February', 'Fevrier': 'February',
    'Mars': 'March', 'Avril': 'April', 'Juillet': 'July',
    'sept. 2023': 'Sep 2023', 'oct. 2023': 'Oct 2023', 'nov. 2023': 'Nov 2023',
    'déc. 2023': 'Dec 2023', 'janv. 2024': 'Jan 2024', 'févr. 2024': 'Feb 2024',
    'mars 2024': 'Mar 2024', 'avr. 2024': 'Apr 2024', 'mai 2024': 'May 2024',
    'juin 2024': 'Jun 2024', 'juill. 2024': 'Jul 2024', 'août 2024': 'Aug 2024',
    'sept. 2024': 'Sep 2024', 'oct. 2024': 'Oct 2024', 'nov. 2024': 'Nov 2024',
    'déc. 2024': 'Dec 2024', 'janv. 2025': 'Jan 2025', 'févr. 2025': 'Feb 2025',
    'mars 2025': 'Mar 2025', 'avril 2025': 'Apr 2025', 'mai 2025': 'May 2025',
    'juin 2025': 'Jun 2025', 'juillet 2025': 'Jul 2025', 'août 2025': 'Aug 2025',
    'septembre 2025': 'September 2025', 'octobre 2025': 'October 2025',
    'novembre 2025': 'November 2025', 'décembre 2025': 'December 2025',
    'janvier 2026': 'January 2026', 'février 2026': 'February 2026',
    'mars 2026': 'March 2026', 'avr. 2026': 'Apr 2026', 'mai 2026': 'May 2026',
    'juin 2026': 'Jun 2026',

    # --------------------------------------------- comptes QuickBooks, revenus
    '4000 Revenus e-commerce': '4000 E-commerce revenue',
    '4010 Shopify Canada': '4010 Shopify Canada',
    '4011 Ventes Shopify Canada': '4011 Shopify Canada sales',
    '4012 Rabais Shopify Canada': '4012 Shopify Canada discounts',
    '4013 Remboursements Shopify Canada': '4013 Shopify Canada refunds',
    '4014 Revenus de livraison Shopify Canada':
        '4014 Shopify Canada shipping revenue',
    '4015 Revenus de pourboire Shopify Canada': '4015 Shopify Canada tip revenue',
    'Total 4010 Shopify Canada': 'Total 4010 Shopify Canada',
    '4020 Shopify Corpo Canada (Manual Orders)':
        '4020 Shopify Corporate Canada (manual orders)',
    '4021 Ventes Shopify Corpo': '4021 Shopify Corporate sales',
    '4022 Rabais Shopify Corpo': '4022 Shopify Corporate discounts',
    '4024 Revenus de livraison Shopify Corpo':
        '4024 Shopify Corporate shipping revenue',
    'Total 4020 Shopify Corpo Canada (Manual Orders)':
        'Total 4020 Shopify Corporate Canada (manual orders)',
    '4030 Shopify USA': '4030 Shopify USA',
    '4031 Ventes Shopify USA': '4031 Shopify USA sales',
    '4032 Rabais Shopify USA': '4032 Shopify USA discounts',
    '4033 Remboursements Shopify USA': '4033 Shopify USA refunds',
    '4034 Revenus de livraison Shopify USA': '4034 Shopify USA shipping revenue',
    '4035 Revenus de pourboire Shopify USA': '4035 Shopify USA tip revenue',
    'Total 4030 Shopify USA': 'Total 4030 Shopify USA',
    '4050 Etsy Canada': '4050 Etsy Canada',
    '4051 Ventes Etsy Canada': '4051 Etsy Canada sales',
    '4052 Revenus de livraison Etsy Canada': '4052 Etsy Canada shipping revenue',
    '4053 Rabais Etsy Canada': '4053 Etsy Canada discounts',
    '4054 Remboursements Etsy Canada': '4054 Etsy Canada refunds',
    'Total 4050 Etsy Canada': 'Total 4050 Etsy Canada',
    '4060 Etsy USA': '4060 Etsy USA',
    '4061 Ventes Etsy USA': '4061 Etsy USA sales',
    '4062 Revenus de livraison Etsy USA': '4062 Etsy USA shipping revenue',
    '4063 Rabais Etsy USA': '4063 Etsy USA discounts',
    'Total 4060 Etsy USA': 'Total 4060 Etsy USA',
    'Total 4000 Revenus e-commerce': 'Total 4000 E-commerce revenue',
    '4200 Ventes corporatives': '4200 Corporate sales',
    "4201 Revenus d'Expédition": '4201 Shipping revenue',
    'Total des revenus': 'Total revenue',

    # ------------------------------------------------- comptes QuickBooks, CMV
    'COÛT DES MARCHANDISES VENDUES': 'COST OF GOODS SOLD',
    '5010 Achats matières et composants': '5010 Purchases of materials and components',
    '5020 Salaires et avantages sociaux - Production':
        '5020 Salaries and benefits — production',
    '5030 Location de matériel': '5030 Equipment rental',
    '5200 Sous-traitance': '5200 Subcontracting',
    '5210 Sous-traitance - Couture': '5210 Subcontracting — sewing',
    'Total 5200 Sous-traitance': 'Total 5200 Subcontracting',
    '5400 Transport sur achats': '5400 Freight on purchases',
    "5500 Frais d'importation": '5500 Import costs',
    '5510 Frais de douane': '5510 Customs duties',
    "Total pour 5500 Frais d'importation": 'Total 5500 Import costs',
    '5900 Inventaires de fin': '5900 Closing inventory',
    '5910 Inventaire de fin - Matières premières':
        '5910 Closing inventory — raw materials',
    '5920 Inventaire de fin - Produits en cours':
        '5920 Closing inventory — work in process',
    '5930 Inventaire de fin - Produits finis':
        '5930 Closing inventory — finished goods',
    'Total 5900 Inventaires de fin': 'Total 5900 Closing inventory',
    '5940 Inventaire de début': '5940 Opening inventory',
    'Total du coût des marchandises vendues': 'Total cost of goods sold',
    'PROFIT BRUT': 'GROSS PROFIT',
    'DÉPENSES': 'EXPENSES',

    # -------------------------------------------- comptes QuickBooks, bilan
    'Actifs à court terme': 'Current assets',
    'Trésorerie': 'Cash and cash equivalents',
    '1001 Compte chèques CAD': '1001 Chequing account CAD',
    '1003 Parts de qualification': '1003 Qualifying shares',
    '1020 Compte Paypal': '1020 PayPal account',
    'Total Trésorerie': 'Total cash and cash equivalents',
    'Comptes clients (CC)': 'Accounts receivable (AR)',
    '1030 Comptes clients (CC)': '1030 Accounts receivable (AR)',
    'Total Comptes clients (CC)': 'Total accounts receivable (AR)',
    '1100 Fonds non-déposés (Balances E-Commerce)':
        '1100 Undeposited funds (e-commerce balances)',
    '1110 Shopify Pending Balances': '1110 Shopify pending balances',
    '1112 Shopify Carried Balances': '1112 Shopify carried balances',
    '1120 Etsy Pending Balances': '1120 Etsy pending balances',
    '1121 Etsy Carried Balances': '1121 Etsy carried balances',
    '1130 Comptes clients (Shopify Manual Orders "Paid")':
        '1130 Accounts receivable (Shopify manual orders, “Paid”)',
    '1131 Comptes clients (Shopify Manual Orders "Pending")':
        '1131 Accounts receivable (Shopify manual orders, “Pending”)',
    'Total 1100 Fonds non-déposés (Balances E-Commerce)':
        'Total 1100 Undeposited funds (e-commerce balances)',
    '1250 Impôts à recevoir': '1250 Income tax receivable',
    '1300 Inventaire - Matières premières': '1300 Inventory — raw materials',
    '1400 Inventaire - Produits en cours': '1400 Inventory — work in process',
    '1500 Inventaire - Produits finis': '1500 Inventory — finished goods',
    '1550 Charges payées d\'avance': '1550 Prepaid expenses',
    '1649 Intérêts Shopify': '1649 Shopify interest',
    'Total Actifs à court terme': 'Total current assets',
    'Actifs à long terme': 'Long-term assets',
    'Installations de production, immobilisations et matériel':
        'Production facilities, property and equipment',
    '1600 Immobilisations': '1600 Capital assets',
    '1610 Matériel informatique': '1610 Computer equipment',
    '1620 Véhicules': '1620 Vehicles',
    '1630 Équipements': '1630 Equipment',
    '1640 Améliorations locatives': '1640 Leasehold improvements',
    'Total 1600 Immobilisations': 'Total 1600 Capital assets',
    '1700 Amortissements cumulés': '1700 Accumulated depreciation',
    '1710 Amortissement cumulé - Matériel informatique':
        '1710 Accumulated depreciation — computer equipment',
    '1720 Amortissement cumulé - Véhicules':
        '1720 Accumulated depreciation — vehicles',
    '1730 Amortissement cumulé - Équipements':
        '1730 Accumulated depreciation — equipment',
    '1740 Amortissement cumulé - Améliorations locatives':
        '1740 Accumulated depreciation — leasehold improvements',
    '1750 Amort. cum équipements': '1750 Accumulated depreciation, equipment',
    'Total 1700 Amortissements cumulés': 'Total 1700 Accumulated depreciation',
    'Total Installations de production, immobilisations et matériel':
        'Total production facilities, property and equipment',
    'Total Actifs à long terme': 'Total long-term assets',
    'Total des actifs': 'Total assets',
    'OBLIGATIONS ET CAPITAL': 'LIABILITIES AND EQUITY',
    'Obligations': 'Liabilities',
    'Comptes fournisseurs': 'Accounts payable',
    '2010 Comptes fournisseurs (CF)': '2010 Accounts payable (AP)',
    'Comptes fournisseurs (CF) - USD': 'Accounts payable (AP) — USD',
    'Total Comptes fournisseurs': 'Total accounts payable',
    '2020 Marges de crédit': '2020 Lines of credit',
    '2021 Marge de crédit (LibreAffaire AccèsD 40k) (Inactif)':
        '2021 Line of credit (LibreAffaire AccèsD 40k) (inactive)',
    '2022 Marge de crédit - EDC LC1 - 150K': '2022 Line of credit — EDC LC1 — 150K',
    'Total 2020 Marges de crédit': 'Total 2020 Lines of credit',
    '2030 Cartes de crédit': '2030 Credit cards',
    '2031 VISA PRINCIPALE (8010 ou 9028)': '2031 MAIN VISA (8010 or 9028)',
    '2032 (EMILIE) VISA 0015': '2032 (EMILIE) VISA 0015',
    '2033 (JULIETTE) VISA 6013': '2033 (JULIETTE) VISA 6013',
    '2034 (ISABELLE) VISA 9017': '2034 (ISABELLE) VISA 9017',
    '6000 Frais généraux': '6000 Overhead',
    '6001 Loyer': '6001 Rent',
    '6005 Frais de bureau': '6005 Office expenses',
    '6010 Fournitures/petits outils': '6010 Supplies and small tools',
    '6011 Transport divers (Rattaché à la production)':
        '6011 Miscellaneous transport (production-related)',
    '6020 Assurances commerciales': '6020 Commercial insurance',
    '6030 Entretien et réparation des équipements':
        '6030 Equipment maintenance and repairs',
    '6040 Frais véhicules': '6040 Vehicle costs',
    '6041 Carburant': '6041 Fuel',
    '6042 Entretien et réparation - Véhicules':
        '6042 Maintenance and repairs — vehicles',
    "6044 Frais d'immatriculations": '6044 Vehicle registration fees',
    'Total 6040 Frais véhicules': 'Total 6040 Vehicle costs',
}

GLOSSAIRE = {**{s: s for s in IDENTIQUE}, **TRADUIT}
