# -*- coding: utf-8 -*-
# (id, titre, badges, hook, storyboard[(plan, tc)], cta, note)
FAM = [
("A","La reconnaissance","Recruter à froid. Le fil se remplit sans CTA.","Taux de commentaires + part de commentaires qui donnent un nom"),
("B","La preuve physique","Crédibilité produit et partages.","Partages et enregistrements"),
("C","Le procédé","Faire taire le scepticisme.","Absence d'objection dans le fil"),
("D","Le gisement","Désamorcer l'écolo, ouvrir la filière.","Offres de matière qualifiées"),
("E","Le microscopique","Expliquer pourquoi ça marche.","Enregistrements"),
("F","Le vivant","Le contenu que personne d'autre ne peut faire.","Portée et partages"),
("G","Les rendez-vous","Republier le catalogue à coût nul.","Rétention d'une semaine à l'autre"),
("H","L'usage réel","Convertir les sceptiques par la performance.","Ventes et questions d'achat"),
("I","La destruction utile","Ouvrir, couper, sacrifier pour montrer.","Partages"),
("J","Le jardin","La porte d'entrée la moins chère.","Enregistrements et ventes de semences"),
("K","L'atelier","Le savoir-faire invisible. Fidélise, ne recrute pas.","Taux de j'aime sur l'audience acquise"),
("L","Le récit et l'absurde","Parler à l'audience déjà là. 1 pour 6.","Qualité des commentaires"),
]

C = [
# ---------------- A ----------------
("A-01","Tout le monde a déjà fait ça",["15","sais"],
 "T'as déjà fait ça quand t'étais petit. Tu sais pas c'est quoi.",
 [("M-01","0-2,5 s"),("M-02","2,5-5 s"),("M-03","5-9 s"),("H-03","9-11 s"),("M-04","11-14 s")],
 "Écris son nom en commentaire.","Aucune phrase d'explication au montage. Si une seule entre, le concept meurt."),
("A-02","Le test du fossé",["15"],
 "Je me suis arrêté sur le bord de la 20. Regarde ce qui pousse là.",
 [("H-04","0-1,5 s"),("T-01","1,5-5 s"),("T-05","5-8 s"),("M-01","8-12 s"),("T-01","12-15 s")],
 "Tague quelqu'un qui a ça dans sa cour.","Dire à 10 s que la matière de la marque vient de champs cultivés."),
("A-03","Personne peut la nommer",["1h"],
 "J'ai demandé à 20 personnes. Deux ont réussi.",
 [("H-05","0-4 s"),("H-05","4-9 s"),("H-03","9-12 s"),("H-05","12-16 s"),("M-01","16-19 s")],
 "Toi, tu le sais ? Écris-le.","Autorisation demandée à chaque personne. Ton complice, jamais moqueur."),
("A-04","Ce que ça vaut / ce que ça vaut pas",["15"],
 "Ça, ça vaut rien. Ça, ça vaut 300 $. C'est la même affaire.",
 [("M-10","0-2 s"),("A-06","4-7 s"),("M-01","7-10 s"),("M-05","10-14 s")],
 "Devine c'est quoi.","Jamais un prix qui n'est pas celui en vigueur sur le site."),
("A-05","Le fossé de Google Maps",["15"],
 "Donne-moi ta ville. Je te trouve la plante en Street View.",
 [("T-03","0-6 s"),("T-01","6-12 s"),("T-03","12-18 s"),("M-06","18-20 s")],
 "Écris ta ville. Je la fais dans la prochaine.","Arc : il faut l'épisode suivant. Aucune adresse résidentielle lisible."),
("A-06","Les faux noms",["15"],
 "Voici les 30 noms que vous lui avez donnés. Un seul est le bon.",
 [("M-04","0-3 s"),("M-04","3-12 s"),("M-01","12-16 s")],
 "Le tien était dedans ?","Pseudos masqués."),
("A-07","Cherche-la dans l'image",["15","risq"],
 "Elle est dans les tableaux, dans les livres. Personne la voit.",
 [("T-03","0-4 s"),("M-06","4-9 s"),("T-01","9-14 s")],
 "Tu l'avais vue avant le cercle ? Oui ou non.","Domaine public vérifié uniquement. Aucune capture de film ni photo de presse."),
("A-08","Le paquet anonyme",["1h"],
 "Touche ça. Devine c'est quoi.",
 [("H-05","0-3 s"),("M-05","3-8 s"),("H-05","8-13 s"),("M-01","13-17 s")],
 "Toi, t'aurais dit quoi ?",""),
# ---------------- B ----------------
("B-01","Le congélateur",["1h","risq"],
 "Une main nue. Une main avec la mitaine. On chronomètre.",
 [("D-04","0-2 s"),("D-01","2-4 s"),("D-05","4-16 s"),("D-03","16-20 s"),("M-06","20-24 s")],
 "Toi, tu tiendrais combien de temps ?","Limite dure 4 min, surveillance hors champ, jamais d'enfant. Aucune promesse de température."),
("B-02","La caméra thermique",["1h"],
 "Une caméra thermique voit la chaleur qui s'échappe. Regarde.",
 [("D-02","0-4 s"),("D-04","4-12 s"),("A-06","12-16 s"),("D-02","16-20 s")],
 "Quel autre morceau je passe au thermique ?","Ce n'est pas une mesure normalisée. Aucun chiffre de performance n'en sort."),
("B-03","Le glaçon",["15"],
 "Trois glaçons. Trois isolants. Lequel fond en premier ?",
 [("M-10","0-4 s"),("D-06","4-18 s"),("M-06","18-22 s")],
 "Devine le gagnant. 1, 2 ou 3 ?","Même épaisseur, même masse, même température de départ — et le montrer."),
("B-04","L'eau qui refuse d'entrer",["15"],
 "Je pousse cette matière au fond d'un verre. Elle va ressortir sèche.",
 [("M-09","0-8 s"),("M-08","8-13 s"),("M-05","13-17 s")],
 "Tu veux voir quoi d'autre dans le verre ?","Jamais « imperméable ». « L'eau glisse dessus »."),
("B-05","La balance",["15"],
 "10 grammes. C'est tout ce qu'il y a dans une mitaine.",
 [("M-12","0-5 s"),("M-06","5-10 s"),("A-06","10-14 s")],
 "Devine le poids avant que je le montre.","Une donnée de labo sur la fibre ne se transfère pas au produit fini."),
("B-06","La compression",["1j","risq"],
 "On écrase cet isolant 1 000 fois. On va voir s'il revient.",
 [("A-01","0-6 s"),("D-05","6-14 s"),("M-06","14-20 s")],
 "Combien de cycles avant que ça lâche ?","Arc : date de la vidéo de résultat fixée AVANT de publier."),
("B-07","Le seau d'eau",["15","risq"],
 "Je vide un seau sur ce manteau. Voyons ce qu'il y a en dessous.",
 [("M-08","0-6 s"),("D-03","6-12 s"),("M-05","12-16 s")],
 "Sec ou mouillé ? Dis-le avant que j'ouvre.","« Résistant à l'eau », jamais « imperméable ». Aucune durée d'exposition suggérée."),
("B-08","La nuit dehors",["1j","sais","risq"],
 "Je dors dehors à −22 avec juste ça.",
 [("D-01","0-4 s"),("H-04","4-14 s"),("H-01","14-22 s"),("D-01","22-27 s")],
 "Tu penses que j'ai tenu jusqu'à quelle heure ?","Quelqu'un réveillé à moins de 20 m. Pas de garantie de température de confort."),
("B-09","Le duel à l'aveugle",["1h","risq"],
 "Deux manteaux. Un coûte trois fois le prix de l'autre. Même test.",
 [("D-04","0-4 s"),("D-01","4-14 s"),("M-06","14-20 s")],
 "Lequel tu prendrais ? A ou B.","Concurrent jamais nommé ni identifiable, jamais dénigré. En cas de doute : ne pas publier."),
("B-10","Le test que le public a réclamé",["15"],
 "Vous m'avez demandé 47 fois de faire ce test-là.",
 [("M-06","0-2 s"),("D-04","2-12 s"),("D-03","12-18 s")],
 "C'est quoi le prochain test ?","N'ouvrir la demande que si la cadence permet de l'honorer."),
# ---------------- C ----------------
("C-01","Du fossé au manteau",["1j"],
 "Ce manteau-là commence dans un fossé.",
 [("H-03","0-1 s"),("T-04","1-5 s"),("M-01","5-7 s"),("A-02","7-11 s"),("A-03","11-14 s"),("A-05","14-19 s"),("A-06","19-22 s"),("H-03","22-25 s")],
 "Il manque une étape. Devine laquelle.","Ordre obligatoire : objet désirable → matière → procédé → objet fini. Le trou est volontaire."),
("C-02","Un kilo, ça donne quoi",["1h"],
 "Un kilo de cette matière. Ça fait combien de mitaines ?",
 [("M-12","0-4 s"),("A-07","4-14 s"),("M-06","14-20 s")],
 "Ton estimation avant que je montre le chiffre ?","Le chiffre doit être vrai et vérifiable en interne."),
("C-03","Le procédé muet",["1h"],
 "Aucune parole. La matière qui tombe, plein cadre, 240 fps.",
 [("A-02","0-3 s"),("A-01","3-8 s"),("A-03","8-12 s"),("A-04","12-16 s"),("A-06","16-20 s")],
 "Carton 2 s : quelle étape tu veux voir en gros plan ?","Sans le carton, la vidéo n'apprend rien (loi 13)."),
("C-04","L'étape que personne devine",["1h","risq"],
 "Vous avez été 300 à demander comment on sépare la soie des graines.",
 [("A-01","0-5 s"),("A-02","5-12 s"),("M-10","12-18 s")],
 "Et les graines, elles vont où, tu penses ?","Décider avant le tournage de ce qui reste hors champ. Un cadrage qui coupe est honnête."),
("C-05","Le rouleau",["15"],
 "Ça, c'est 40 mètres de chaleur.",
 [("A-03","0-6 s"),("M-04","6-12 s"),("T-03","12-16 s")],
 "Devine combien de mètres.",""),
("C-06","Ce qui se fait ici, ce qui se fait ailleurs",["1h","risq"],
 "Cette partie-là est faite ici. Cette partie-là, non. Je t'explique pourquoi.",
 [("M-10","0-6 s"),("H-01","6-24 s"),("A-06","24-30 s")],
 "T'as-tu des questions là-dessus ?","Jamais « fabriqué au Québec » pour un produit assemblé ailleurs. Jamais « rien ne change »."),
("C-07","L'insert, filmé comme une pub d'auto",["15"],
 "Le manteau se démonte. C'est ça qui change tout.",
 [("A-06","0-4 s"),("A-06","4-8 s"),("A-06","8-12 s"),("M-11","12-16 s")],
 "Tu le mettrais quand ? Novembre ou janvier ?",""),
# ---------------- D ----------------
("D-01c","Le champ d'automne",["1h","sais"],
 "Ce champ-là, c'est 40 hectares de mauvaise herbe. Payée.",
 [("T-07","0-3 s"),("T-02","3-6 s"),("T-04","6-11 s"),("T-03","11-16 s"),("T-05","16-20 s")],
 "T'en as-tu, toi, dans ton champ ?","Désamorçage avant la 8e s : récolte à l'automne, après la ponte. Champ sec à l'image."),
("D-02c","L'agriculteur qui a dit oui",["1j"],
 "Lui, y'a douze ans, il arrachait ça. Aujourd'hui il en sème.",
 [("H-06","0-6 s"),("H-03","6-12 s"),("T-03","12-20 s"),("H-06","20-28 s")],
 "Tu connais un producteur qui devrait essayer ? Tague-le.","Aucun chiffre de revenu sans accord écrit. Montage remis avant publication."),
("D-03c","La récolte mécanique",["1j","sais"],
 "Y'a pas de machine faite pour ça. Alors on en a fabriqué une.",
 [("T-03","0-5 s"),("A-01","5-12 s"),("A-08","12-18 s")],
 "T'as une idée pour régler ça ?","Attire des apports opérationnels réels."),
("D-04c","Le champ qui n'existe plus",["1h"],
 "Ici, y'avait un champ. Il a été détruit en 2018.",
 [("T-03","0-5 s"),("H-01","5-22 s"),("T-01","22-26 s")],
 "T'en avais-tu entendu parler ?","Échec collectif de filière, jamais des fautes individuelles. On ne nomme personne."),
("D-05c","La fenêtre de récolte",["15","sais"],
 "On a deux semaines. Après, tout est parti au vent.",
 [("M-10","0-4 s"),("M-01","4-8 s"),("M-01","8-12 s"),("M-01","12-16 s")],
 "Laquelle est la bonne ? 1, 2 ou 3.",""),
("D-06c","Le sac de 20 kg",["15"],
 "20 kilos. Devine la grosseur du sac.",
 [("T-06","0-4 s"),("M-12","4-9 s"),("A-02","9-14 s")],
 "Devine le poids.",""),
("D-07c","Le gisement qu'on cherche",["15","risq"],
 "On cherche des champs. Si t'en as, dis-le.",
 [("T-03","0-4 s"),("T-01","4-9 s"),("M-06","9-13 s")],
 "Écris ta région.","Ne pas publier tant que le lien de contact n'est pas en bio."),
# ---------------- E ----------------
("E-01","Le tube creux",["15"],
 "Cette fibre-là est creuse. C'est pour ça qu'elle est chaude.",
 [("M-05","0-2 s"),("M-07","2-12 s"),("M-06","12-16 s")],
 "Quelle autre matière je passe au microscope ?","Expliquer le mécanisme, ne pas promettre une performance."),
("E-02","Le duel au microscope",["15"],
 "Duvet, laine, polyester, et la nôtre. Même grossissement.",
 [("M-07","0-4 s"),("M-07","4-8 s"),("M-07","8-12 s"),("M-07","12-16 s")],
 "Laquelle t'aurais choisie ?","Ne pas dénigrer les autres fibres. « Structure différente », pas « mauvaises »."),
("E-03","La cire",["15"],
 "Cette fibre est enduite d'une cire naturelle. C'est pour ça que l'eau glisse.",
 [("M-08","0-5 s"),("M-07","5-11 s"),("M-03","11-16 s")],
 "Tu savais que c'était pour ça ? Oui ou non.",""),
("E-04","L'électricité statique",["15"],
 "Ces fibres-là se repoussent entre elles. Regarde ce qui arrive.",
 [("M-05","0-5 s"),("M-02","5-11 s"),("M-03","11-15 s")],
 "Ça te rappelle quoi ?",""),
("E-05","Le comptage des graines",["15"],
 "Combien de graines dans une gousse ? On compte.",
 [("M-01","0-3 s"),("V-05","3-18 s"),("M-06","18-22 s")],
 "Ton estimation avant que j'arrive au bout ?","Carton posé à 4 s, pas à la fin."),
("E-06","La pollinisation impossible",["1h","sais"],
 "Le pollen part en petits paquets. L'insecte doit le décrocher avec sa patte.",
 [("V-04","0-8 s"),("M-07","8-16 s"),("V-04","16-22 s")],
 "T'as déjà senti cette fleur-là ?",""),
# ---------------- F ----------------
("F-01","La feuille qui disparaît",["1h","sais","risq"],
 "Cette chenille-là mange une seule plante au monde. Celle-là.",
 [("V-01","0-4 s"),("V-01","4-16 s"),("M-07","16-22 s")],
 "T'en as-tu déjà vu une, en vrai ? Oui ou non.","Aucune manipulation, aucun prélèvement, aucune LED directe."),
("F-02","La chrysalide",["1j","sais","risq"],
 "J'ai laissé une caméra pendant huit jours.",
 [("V-02","0-6 s"),("V-02","6-18 s"),("V-03","18-24 s")],
 "Tu veux voir la suite ?","Ne pas déplacer une chrysalide. Si filmer exige d'intervenir, on ne filme pas."),
("F-03","Le trajet",["1h"],
 "Cet insecte-là part de ton jardin et se rend au Mexique.",
 [("V-03","0-4 s"),("T-03","4-12 s"),("V-04","12-20 s")],
 "T'en as vu combien cet été ? Écris le chiffre.","Ne pas confondre population de l'est et de l'ouest. Aucun décompte sans année ni source."),
("F-04","Les colocataires",["1h","sais"],
 "J'ai filmé une seule fleur pendant une heure. Compte les espèces.",
 [("V-04","0-5 s"),("V-04","5-14 s"),("V-04","14-20 s")],
 "T'en reconnais combien ?",""),
("F-05","Le poison",["15"],
 "Elle mange le poison pour devenir immangeable.",
 [("M-08","0-5 s"),("V-01","5-14 s"),("V-03","14-19 s")],
 "Tu savais ça ?","Le latex est irritant : une phrase, sans dramatiser."),
("F-06","L'œuf",["1h","sais"],
 "Regarde en dessous des feuilles. Y'a peut-être ça chez toi.",
 [("V-01","0-4 s"),("M-07","4-12 s"),("V-04","12-17 s")],
 "Va voir sous tes feuilles. Reviens me dire.","CTA à action différée : produit des commentaires pendant des semaines."),
("F-07","Ce qu'il reste en novembre",["15","sais"],
 "En novembre, y'a plus rien. C'est là qu'on récolte.",
 [("T-07","0-5 s"),("T-02","5-10 s"),("T-05","10-16 s")],
 "T'avais-tu cette question-là ?","Vidéo à épingler : elle sert de réponse standard à l'objection habitat."),
# ---------------- G ----------------
("G-01","Le meilleur vendeur de la semaine",["15"],
 "Meilleur vendeur de la semaine : ______.",
 [("H-03","0-1 s"),("A-06","1-8 s"),("A-05","8-12 s"),("M-10","12-18 s")],
 "C'est quoi ton préféré ?","Tenir la promesse : expliquer POURQUOI celui-là. Prix et adresse à l'image."),
("G-02","La couleur SERA",["15","risq"],
 "Le commentaire avec le plus de likes SERA la prochaine couleur.",
 [("M-10","0-4 s"),("A-01","4-14 s"),("A-02","14-22 s"),("H-03","22-28 s")],
 "Écris ta couleur. Celle avec le plus de likes, je la fais.","Enjeu annoncé AVANT la révélation. Engagement de production réel."),
("G-03","Le lundi du fossé",["15"],
 "Semaine 12. Cette semaine, on est à ______.",
 [("H-04","0-2 s"),("T-01","2-9 s"),("M-01","9-14 s")],
 "Écris ta ville pour la semaine prochaine.","Décider du nombre d'épisodes avant de commencer, et l'annoncer."),
("G-04","Le classement des pires",["15"],
 "Top 5 des affaires qui gardent le moins chaud. Numéro 5 : ______.",
 [("M-10","0-3 s"),("D-04","3-10 s"),("D-04","10-17 s"),("M-06","17-22 s")],
 "Qu'est-ce qui manque dans le top 5 ?","Liste affichée dès la première image : ×3,1 de commentaires."),
("G-05","Je réponds à un commentaire",["15"],
 "Ce commentaire-là mérite une vidéo au complet.",
 [("M-06","0-2 s"),("H-01","2-10 s"),("D-03","10-18 s")],
 "Pose la tienne.","Répondre aux objections dures, pas seulement aux compliments."),
("G-06","Le compteur de la saison",["15","sais"],
 "Jour 14 de la récolte. On est rendus à ______ kilos.",
 [("T-06","0-3 s"),("M-12","3-7 s"),("M-06","7-11 s")],
 "On va-tu y arriver ?","Le chiffre final se publie même s'il est décevant."),
("G-07","Le duel de la semaine",["15"],
 "Cette semaine : ______ contre ______. Même test.",
 [("D-04","0-3 s"),("D-01","3-12 s"),("M-06","12-17 s")],
 "Lequel gagne la semaine prochaine ?","Construit un tournoi sur une saison, sans aucune nouveauté."),
("G-08","La commande la plus bizarre",["15"],
 "Quelqu'un a commandé 40 sachets de graines pour un mariage.",
 [("T-06","0-3 s"),("H-03","3-10 s"),("A-07","10-15 s")],
 "Tu l'utiliserais pour quoi, toi ?","Aucune donnée personnelle à l'écran."),
# ---------------- H ----------------
("H-01c","La pêche sur glace",["1j","sais"],
 "−24, huit heures sur la glace. On va voir.",
 [("H-04","0-4 s"),("D-01","4-9 s"),("H-06","9-18 s"),("M-11","18-23 s"),("H-06","23-30 s")],
 "Tu pêches où, toi ?","Un témoignage n'est pas une promesse de performance."),
("H-02c","Les gars de la construction",["1j","risq"],
 "J'ai donné des gants à des charpentiers pendant trois mois. Regarde l'état.",
 [("M-10","0-4 s"),("M-06","4-12 s"),("H-05","12-20 s")],
 "Tu ferais quoi de mieux ?","Produit en développement : le présenter comme tel. Aucune date de sortie promise."),
("H-03c","L'autobus scolaire à 7 h 10",["15","sais"],
 "Le vrai test d'une mitaine, c'est l'arrêt d'autobus à −18.",
 [("D-01","0-3 s"),("H-04","3-10 s"),("D-05","10-16 s")],
 "C'est quoi ton pire moment de froid de l'hiver ?",""),
("H-04c","La glacière à l'envers",["15","sais"],
 "Le même isolant qui te garde au chaud l'hiver garde ta bière froide l'été.",
 [("D-01","0-4 s"),("D-06","4-14 s"),("D-04","14-20 s")],
 "Combien d'heures, ton estimation ?",""),
("H-05c","Le lavage, montré",["15"],
 "Oui, ça se lave. Voici exactement comment.",
 [("H-03","0-6 s"),("D-06","6-14 s"),("M-10","14-19 s")],
 "T'as d'autres questions d'entretien ?","Une affirmation ne ferme pas une objection. Une démonstration, oui. À épingler."),
("H-06c","Le manteau après trois ans",["1h"],
 "Elle porte ce manteau-là depuis trois hivers. Regarde.",
 [("M-10","0-4 s"),("M-06","4-12 s"),("H-05","12-18 s")],
 "Depuis combien de temps t'as le tien ?",""),
("H-07c","Le POV du matin de janvier",["15","sais"],
 "Aucune parole. La porte, le froid, le grattoir. Texte : « −27 ».",
 [("H-04","0-8 s"),("M-11","8-15 s"),("H-04","15-20 s")],
 "Carton 2 s : c'était combien chez toi à matin ?","Carton obligatoire, sinon le format n'apprend rien."),
("H-08c","Le sceptique",["1h","risq"],
 "Je voulais quelqu'un qui allait me dire que c'est de la marde.",
 [("H-05","0-5 s"),("D-01","5-14 s"),("H-05","14-22 s")],
 "T'aurais dit quoi à sa place ?","Il faut accepter un verdict négatif et le publier. Sinon, ne pas lancer."),
# ---------------- I ----------------
("I-01","J'ai coupé un manteau en deux",["1h","risq"],
 "J'ai coupé un manteau à 300 $ en deux. Pour que tu voies ce qu'il y a dedans.",
 [("H-03","0-2 s"),("A-04","2-6 s"),("D-03","6-9 s"),("M-06","9-18 s"),("M-05","18-22 s")],
 "Quel autre morceau je coupe en deux ?","Composition réelle à l'écran : certains produits ne sont pas 100 % de notre fibre."),
("I-02","L'autopsie de la mitaine",["15"],
 "On découd une mitaine au complet. Compte les pièces.",
 [("M-10","0-5 s"),("A-04","5-12 s"),("A-07","12-18 s")],
 "Devine le nombre de morceaux avant la fin.",""),
("I-03","Le produit raté",["15"],
 "Ça, c'est un prototype qui a jamais marché. Je vais te dire pourquoi.",
 [("M-06","0-4 s"),("A-08","4-12 s"),("H-01","12-20 s")],
 "T'aurais fait quoi à ma place ?","Montrer le raté, pas le raconter. Un aveu par carton coûte plus cher que la casse."),
("I-04","Le sac de retours",["15"],
 "Voici tout ce qui nous est revenu ce mois-ci. Et pourquoi.",
 [("T-06","0-4 s"),("M-06","4-13 s"),("M-10","13-18 s")],
 "Ça, tu l'achèterais à rabais ? Oui ou non.",""),
("I-05","La réparation",["15"],
 "Un trou. Six minutes. Regarde.",
 [("M-06","0-3 s"),("A-05","3-12 s"),("D-05","12-17 s")],
 "T'as un morceau à réparer ? Montre-le-moi.",""),
("I-06","Le sacrifice au feu",["1h","risq"],
 "Une fibre végétale et une fibre de pétrole. Une flamme. Deux comportements.",
 [("D-04","0-4 s"),("D-03","4-12 s"),("M-06","12-17 s")],
 "Lequel tu porterais ?","RISQUE MAXIMAL. Aucune affirmation de résistance au feu. Extérieur, extincteur dans le cadre. En cas d'hésitation : ne pas faire."),
# ---------------- J ----------------
("J-01","Il faut qu'elles gèlent",["15","sais","risq"],
 "Si tu sèmes ces graines-là au printemps, y'a rien qui va pousser.",
 [("M-05","0-4 s"),("H-03","4-11 s"),("D-06","11-16 s"),("M-10","16-20 s")],
 "Tu sèmes quand, toi ? Écris le mois.","Arc de six mois. Repère photo + GPS pour refaire le cadrage au printemps."),
("J-02","La bombe qui pousse",["15"],
 "On lance ça dans un terrain vague. On revient dans 8 semaines.",
 [("M-01","0-4 s"),("D-06","4-14 s"),("T-08","14-20 s")],
 "Où tu lancerais la tienne ?","Trois vidéos, un seul geste. L'arc le plus facile à honorer."),
("J-03","Ce qu'il faut pas faire",["15"],
 "Trois erreurs. La troisième, tout le monde la fait.",
 [("M-10","0-3 s"),("H-03","3-11 s"),("T-01","11-17 s")],
 "Laquelle t'as déjà faite ? 1, 2 ou 3.","Plante indigène, pas exotique envahissante. La nuance est botanique et elle compte."),
("J-04","Le jardin de quelqu'un d'autre",["1h","sais"],
 "Elle a semé nos graines il y a trois ans. Regarde son terrain.",
 [("T-02","0-5 s"),("V-04","5-13 s"),("H-05","13-20 s")],
 "Envoie-moi une photo du tien.","Autorisation écrite."),
("J-05","Le sachet gratuit",["15"],
 "Au début, on en mettait un gratuit dans chaque commande. Le monde a redemandé.",
 [("H-03","0-5 s"),("A-07","5-13 s"),("H-01","13-22 s")],
 "T'en as-tu déjà reçu un ?","Format récit : un pour six."),
("J-06","Le mur de sachets",["15"],
 "Voici tous les sachets qu'on prépare cette semaine.",
 [("A-07","0-4 s"),("V-05","4-12 s"),("M-06","12-17 s")],
 "Devine combien il y en a.",""),
("J-07","Le trottoir",["15"],
 "Personne l'a plantée. Elle est là pareil.",
 [("T-01","0-4 s"),("T-02","4-9 s"),("M-01","9-14 s")],
 "T'en as-tu une proche de chez toi ? Dis-moi la rue.",""),
# ---------------- K ----------------
("K-01","La machine qui existait pas",["1h"],
 "Cette machine-là existe pas. On l'a faite.",
 [("A-01","0-5 s"),("A-08","5-13 s"),("H-03","13-19 s")],
 "Tu réglerais ça comment ?","Attire des apports opérationnels et des offres de partenariat."),
("K-02","Le bruit de l'atelier",["15"],
 "Aucune parole. Le son direct, plein volume, dès l'image 1.",
 [("M-11","0-4 s"),("A-05","4-9 s"),("M-11","9-14 s"),("A-01","14-19 s"),("M-11","19-23 s")],
 "Carton 2 s : c'est lequel, ton préféré ?","Sans le carton, ce format ne produit rien d'exploitable."),
("K-03","Une journée",["1j"],
 "6 h 40.",
 [("H-04","0-4 s"),("A-01","4-14 s"),("A-07","14-22 s"),("H-03","22-28 s")],
 "Tu commences à quelle heure, toi ?","Inclure les moments plates. C'est ce qui rend la journée vraie."),
("K-04","La commande qui part",["15"],
 "Celle-là s'en va au Nouveau-Mexique.",
 [("H-03","0-4 s"),("A-07","4-11 s"),("T-03","11-16 s")],
 "T'es d'où, toi ?","Région ou pays seulement. Jamais l'adresse ni le nom."),
("K-05","L'atelier vide",["1h","risq"],
 "Y'avait huit personnes ici.",
 [("A-07","0-5 s"),("H-01","5-25 s"),("A-03","25-30 s")],
 "T'as déjà eu à démonter quelque chose que t'avais monté ?","Ne pas se servir de la difficulté pour vendre. Ne jamais nommer une personne mise à pied."),
("K-06","Le contrôle qualité",["15"],
 "Sur 200, on en refuse combien ?",
 [("A-07","0-4 s"),("M-06","4-12 s"),("M-10","12-17 s")],
 "Tu l'aurais acceptée, toi ? Oui ou non.",""),
# ---------------- L ----------------
("L-01","Le démarrage à froid",["15"],
 "La parole a déjà commencé quand le plan apparaît.",
 [("H-01","0-15 s"),("A-01","15-20 s"),("H-01","20-40 s")],
 "Question ouverte, jamais un lien commercial.","Bat le cold-open : +22 % vues, +86 % commentaires, +84 % partages."),
("L-02","Le cold-open d'archives",["15"],
 "8 s d'archives montées serré avant le premier mot.",
 [("A-07","0-8 s"),("H-01","8-30 s"),("A-06","30-36 s")],
 "Description-question obligatoire.","Fait mémoriser (+74 % d'enregistrements) mais coûte 18 % de portée. A/B n°1."),
("L-03","La chaise du fossé",["15"],
 "J'ai apporté une chaise de bureau dans un fossé. Laissez-moi vous expliquer.",
 [("T-01","0-4 s"),("H-01","4-14 s"),("M-01","14-19 s")],
 "Prochaine réunion, on l'amène où ?","L'absurde ne marche que si la forme est parfaitement sobre."),
("L-04","Le service à la clientèle du champ",["15"],
 "Bonjour, service à la clientèle. [en tuque, debout dans un champ]",
 [("T-02","0-3 s"),("H-01","3-13 s"),("M-06","13-18 s")],
 "Pose ta question, je réponds dans le champ.","Règle une objection ET fait rire. Deux formats en un."),
("L-05","Les deux montages",["15"],
 "Méthode, pas concept : chaque tournage produit deux montages, publiés le même jour.",
 [("D-04","montage A"),("D-04","montage B")],
 "Une seule variable change.","Variables : ouverture · description · CTA · sous-titres · durée. Consignée AVANT publication."),
("L-06","La révélation — final de saison",["1h","risq"],
 "Ça fait six mois que je refuse de le dire à voix haute.",
 [("M-04","0-10 s"),("M-01","10-16 s"),("H-01","16-40 s")],
 "Tu l'avais deviné quand ?","Se prépare dès la 1re vidéo : capture de chaque fil, dossier dédié."),
("L-07","Le fil de commentaires filmé",["15"],
 "Vous vous êtes obstinés dans les commentaires. Je vais trancher.",
 [("M-06","0-3 s"),("D-04","3-12 s"),("D-03","12-18 s")],
 "Qui avait raison ?",""),
("L-08","Ce que je referais pas",["15","risq"],
 "Trois décisions que je referais pas. La deuxième m'a coûté cher.",
 [("H-01","0-20 s"),("A-08","20-26 s"),("H-01","26-45 s")],
 "C'est quoi, la tienne ?","Aucun chiffre financier interne. Le coût se nomme en temps et en fierté, pas en dollars."),
]
