# -*- coding: utf-8 -*-

PLANS = [
("M","Matière et macro",[
 ("M-01","L'ouverture de gousse","Macro 12 cm, fond noir, lumière rasante 45°, 240 fps. Le plan signature."),
 ("M-02","Le contre-jour","Source derrière la matière, sous-exposer 1,5 IL. Les fibres deviennent des filaments."),
 ("M-03","La soie qui flotte","Pièce noire, un faisceau horizontal, soie lâchée au-dessus. Ne pas suivre."),
 ("M-04","Le tapis de soie","Plongée 40 cm, travelling latéral lent. Fond, transition, respiration."),
 ("M-05","La main dans la matière","Entrée par le bas, geste lent. Filmer 3 vitesses, garder la bonne."),
 ("M-06","L'échelle","Objet familier à côté de la matière. Dans le même plan, jamais en coupe."),
 ("M-07","Le microscope","USB 200–400×. Mise au point réglée AVANT l'enregistrement."),
 ("M-08","La goutte","Compte-gouttes hors champ, 240 fps. 1 prise nette sur 10."),
 ("M-09","L'immersion","Caméra à hauteur d'eau, fond blanc. La bulle d'air est le sujet."),
 ("M-10","La comparaison à trois","Trois échantillons alignés, étiquetés. Seul plan autorisé à être fixe."),
 ("M-11","Le froissement","Micro à 15 cm, casque obligatoire. Le son est le sujet."),
 ("M-12","La pesée","Balance 0,1 g, afficheur et matière dans le même cadre."),
]),
("T","Terrain et champ",[
 ("T-01","Le fossé","Hauteur de plante 30–80 cm, route floue derrière. Le banal est l'argument."),
 ("T-02","Le champ, contre-plongée","Caméra au sol, tiges vers le ciel. Échelle impossible autrement."),
 ("T-03","Le champ, vu d'en haut","Perche 4 m ou drone. Une ascension, 6 à 8 s utilisables."),
 ("T-04","La marche","Hauteur de hanche, plantes qui frôlent l'objectif. Meilleure transition."),
 ("T-05","La cueillette","Serré main + gousse, tige qui casse. Son direct, 4 prises."),
 ("T-06","Le sac qui se remplit","Plan fixe, gousses une à une puis en masse. Accéléré sur la fin."),
 ("T-07","Le vent","Champ sec, soleil bas derrière, soie qui part. Ne pas stabiliser."),
 ("T-08","Le contraste des saisons","Même cadrage, même trépied, 3 moments. GPS + photo de repère."),
]),
("A","Atelier et procédé",[
 ("A-01","La machine qui tourne","Serré sur la pièce mobile, pas sur la machine. Flou naturel conservé."),
 ("A-02","La matière qui tombe","Contre-plongée légère, chute dans un bac, 120 fps."),
 ("A-03","Le rouleau","Latéral, caméra à contresens du déroulé pour doubler la vitesse."),
 ("A-04","La coupe","Plongée serrée sur la lame. Un seul passage au montage."),
 ("A-05","L'aiguille","Macro machine à coudre, 120 fps, lumière ajoutée obligatoire."),
 ("A-06","L'insert qui entre","Le geste-signature du manteau. Une seule prise fluide."),
 ("A-07","La pile qui monte","Time-lapse 1 img / 2 s. 30 min de tournage pour 4 s utiles."),
 ("A-08","La panne","Ce qui bloque, s'encrasse, casse. Capté, jamais rejoué."),
]),
("H","Humain",[
 ("H-01","Face caméra, atelier derrière","Debout, 1,2 m, hauteur d'yeux. Jamais assis derrière un bureau."),
 ("H-02","Le regard complice","1/10 de seconde après un raté. Se récupère au dérushage."),
 ("H-03","Les mains seules","Sans visage. Le geste est plus intéressant que la personne."),
 ("H-04","Le POV","Hauteur de front, stabilisation max. Ce que la personne voit."),
 ("H-05","L'invité qui ne sait pas","Matière tendue sans explication, filmé en réaction. Le meilleur rendement."),
 ("H-06","L'agriculteur","Dans son champ, hauteur d'yeux. Une question, jamais un texte."),
]),
("D","Démonstration et test",[
 ("D-01","Le thermomètre","Afficheur ET sujet dans le même cadre, sinon le test ne prouve rien."),
 ("D-02","La caméra thermique","Distance fixe, échelle de couleurs toujours visible."),
 ("D-03","Le contact","Le moment où ça touche ou ça cède. Ralenti, et toujours montré."),
 ("D-04","Le duel côte à côte","Même cadre, étiquetés. Jamais deux prises séparées montées ensemble."),
 ("D-05","Le chronomètre","Compteur démarré au premier contact. Rend mesurable un test qui ne l'est pas."),
 ("D-06","La glace","Time-lapse, plan fixe absolu, repère de niveau visible."),
 ("D-07","La rupture","240 fps, cadre large pour la direction, recadrage en post."),
]),
("V","Vivant",[
 ("V-01","La chenille qui mange","Latéral strict, lumière douce diffusée. Aucune manipulation."),
 ("V-02","La chrysalide","Trépied verrouillé, plusieurs jours, alimentation continue."),
 ("V-03","L'envol","240 fps, mise au point pré-réglée. Compter 30 tentatives."),
 ("V-04","La fleur et ses visiteurs","Plan fixe 60 min, on coupe sur chaque insecte. Un seul cadrage."),
 ("V-05","Le comptage","Plongée, éléments déplacés un à un, compteur à l'écran."),
]),
]

LOIS = [
 ("1","L'objet nommé et montré<br>en 1<sup>re</sup> seconde","2.04","×2,04 de vues","Même tournage, deux montages. 261 500 vues contre 128 200, à taux de j'aime identique."),
 ("2","L'origine montrée avant<br>qu'on la questionne","3.0","objection ×3","Sans mention de provenance, l'objection monte au 2<sup>e</sup> rang du fil. Avec, elle disparaît."),
 ("3","Promettre une limite,<br>jamais une victoire","145","×145 de vues","Le seul test qui cherche la limite et montre le produit céder : 1,2 M de vues, 7,46 % de j'aime."),
 ("4","Le procédé muet ferme<br>le scepticisme et la bouche","0","0 négatif / 0 question","16 s sans parole : 15 messages, 0 négatif. Et zéro curiosité verbalisée. Laisser un trou."),
 ("5","La preuve sociale<br>AVANT la démonstration","3.3","×3,3 de j'aime","Même procédé filmé deux fois. Produit désirable d'abord : ×2 vues, ×3,3 j'aime, ×6,8 partages."),
 ("6","Question : dans la vidéo,<br>à la fin, au « tu », en un mot","64","×64 de commentaires","Triptyque tourné le même jour. 10,81 commentaires / 10 000 vues contre 0,17."),
 ("7","« SERA », pas « serait »","99","99 % des j'aime","Le vote-contrat capte 99 % des j'aime du fil et donne une décision nette. Le conditionnel, rien."),
 ("8","Ne jamais demander<br>la permission","0","0 réponse / 21","« On devrait en faire d'autres ? » : 0 sur 12, puis 0 sur 9. Répondre oui ne rapporte rien."),
 ("9","Faire taguer le public,<br>ne pas taguer soi-même","21.8","×21,8 de densité","25 succursales taguées : 1 commentaire. Un CTA de 4 s : 37 nominations sur 48."),
 ("10","Un tag notifie, il ne crée<br>pas d'audience","51","51 % des j'aime","Le seul partenariat qui marche : enseigne dans le hook ET logo plein cadre."),
 ("11","Sous-titres réécrits<br>à la main, toujours","46","46 / 135 vidéos","Le nom du produit et des partenaires déformé dans 46 transcriptions sur 135."),
 ("12","Le récit sature,<br>la démonstration recrute","2.65","×2,65 de vues","Trois récits atterrissent à 1,6 % d'écart de vues. Plafond structurel. Ratio : 1 récit / 6 démos."),
 ("13","L'ASMR fait de la portée<br>et rien d'autre","4","÷4 commentaires","291 j'aime par commentaire contre 126. Correctif : un carton de 2 s à la fin."),
 ("14","Deux montages le même jour,<br>oui. Le remake, non.","2","÷2 de j'aime","Doublon du jour : 162 700 vues, 0 reproche. Remake 7 mois plus tard : taux de j'aime divisé par 2."),
]
